DjangoGirls/tutorial

- pl/python_introduction/README.md
Format dictionaries with one key:value pair per line.
Regarding to issue #212
> Format dictionaries

- pl/python_introduction/README.md
Some keywords were displayed like this: ~~~for~~~ instead of this: `for`.
> Minor formatting corrections

- pl/deploy/README.md
- pl/intro_to_command_line/README.md
- pl/python_introduction/README.md
* fix code formatting in chapter 2 - all the code lines weren't properly displayed
* add missing information about python binary usage on Windows
* add alternative install path for Git on Windows
> Small fixes in Polish version.

- en/extend_your_application/README.md
- pl/extend_your_application/README.md
- uk/extend_your_application/README.md
One of the attendees submitted this change to not have the empty div appear if there is no date.
No idea about frontend, just passing things along.
> Don't include empty date div if there is no date

- en/deploy/README.md
Merge two changes of mysite/settings.py file together to one block of code. Previous version was confusing for girls.
> Deploy - Merge changes in mysite/settings.py

- en/django_orm/README.md
As mentioned in issue #282, we now have stuff in the dev database at this point in the tutorial.
These changes reword things slightly so it makes a bit more sense and avoids duplicate data being created or confusion.
:cake:
> Reword tutorial to support stuff in database

- README.md
- en/README.md
Missing dot and capital letter
> Grammar fix

- en/extend_your_application/README.md
Added a "post" wrapper div in post_detail.html
> Changed code for post_detail.html

- en/html/README.md
Hi there, love the tutorial! Had only this one minor issue (might be just me but worth checking):
When I came to this point in the tutorial I tried running the "git add -A ." command and it wouldn't stage all of my modified files. It turns out I was in the wrong directory and I didn't realise this was a problem.
> Explicitly state the directory we should be in

- fr/SUMMARY.md
> Fixed link to "7. Installation de django"

- en/python_introduction/README.md
Tiny suggestion, assuming original author has English as a second language, apologies if not.  "less than" and "less than or equal to" are the ways that < and <= are usually put into words, at least in my experience.  compare, eg, the unittest library which has "assertGreater" and "assertLess".
With that said, I like "smaller" too!
> (tiny thing) "less than" vs "smaller than" as words for <

- fr/django_models/README.md
- fr/django_orm/README.md
> [fr] [django_models] Fixed incorrect file name.

- en/django_start_project/README.md
tested with Baptiste and Ola yesterday. cf #165
> No need to set USE_TZ = False (fixed #165)

- en/python_introduction/README.md
In markdown / gitbook, there is a syntax for specifying that a codeblock uses a particular syntax -- it uses
```python
code here
```
I've made the changes to the python intro (cf "save it!" section), just for the bits where we save code into a file.  Can do more chapters if y'all are happy with it.
> Syntax-highlight Python code blocks

- en/code_editor/README.md
- en/python_introduction/README.md
Some tweaks suggested by @HonzaKral -- explain syntax highlighting and why it's useful, the first time we use an editor in the python intro chapter.
Also a brief discussion of why we need a text editor, in the editor installation chapter
> Mention syntax highlighting, and why we install an editor in the first place

- en/css/README.md
- en/django_admin/README.md
- en/django_forms/README.md
- en/django_models/README.md
- en/django_orm/README.md
- en/django_start_project/README.md
- en/django_templates/README.md
- en/django_urls/README.md
- en/django_views/README.md
- en/dynamic_data_in_templates/README.md
- en/html/README.md
- en/template_extending/README.md
This is a replacement for #337, removing a couple of things that had nothing to do with syntax highlighting.  Should be clean.  To double-check, I've found `git diff -w` gives good output.
> Syntax-highlight all the code listings.

- en/django_start_project/README.md
Changed path of django-admin script for Windows and moved note section before command (so note about appending '.' to the end of the command will be read earlier and will not mess project - one of workshop participants told me it will be more clear)
> Changes in startproject section

- pl/deploy/README.md
- pl/django_orm/README.md
1. It's better to confirm current working directory before initializing Git repo
2. In Chapter 10 some Posts have been added (via Django admin panel), so in Chapter 11 we will see them in console
> minor pl-en inconsistencies

- en/deploy/README.md
- en/django_forms/README.md
- en/extend_your_application/README.md
- en/html/README.md
hopefully addresses #360 and a few other things...
> PythonAnywhere deploy: some tweaks and improvements based on experiences from first workshop

- en/django_forms/README.md
if we dont add published date for new and edited posts, they get filtered out in the post_list section
> add published date with filled forms

- en/intro_to_command_line/README.md
Used Hemingway App to fix hard-to-read sentences and grammar.
:dancer:
> Run command line chapter through hemingway

- en/python_introduction/README.md
Improved hard-to-read text and grammar.
:grimacing:
> Run python introduction chapter through Hemingway

- en/django_admin/README.md
Improved hard-to-read text and grammar.
:shaved_ice:
> Run django admin chapter through hemingway

- en/python_introduction/README.md
Oops! Missed a word
:crying_cat_face:
> Fixed missing word

- pl/django/README.md
> correct sentence

- en/python_installation/README.md
Lack of explicit phrasing and colon rendered the previous
version a little unclear. Fixes issue #382.
> Clarify connection between paragraph and its following helper image

- en/python_installation/README.md
Improved hard to read text and grammar in Python Installation chapter.
:tada:
> Run python installation chapter through hemingway

- en/how_the_internet_works/README.md
Fixed grammar and wording using Hemingway app to highlight hard-to-read areas.
:cake:
> Run internet chapter through hemingway

- en/deploy/README.md
> Add explanations of placeholder text

- book.json
- en/css/README.md
- en/deploy/README.md
- en/django_admin/README.md
- en/django_forms/README.md
- en/django_installation/README.md
- en/django_models/README.md
- en/django_orm/README.md
- en/django_start_project/README.md
- en/django_templates/README.md
- en/django_urls/README.md
- en/django_views/README.md
- en/dynamic_data_in_templates/README.md
- en/extend_your_application/README.md
- en/html/README.md
- en/intro_to_command_line/README.md
- en/python_installation/README.md
- en/python_introduction/README.md
- en/template_extending/README.md
> Added filenames over all code blocks.

- pt/css/README.md
- pt/django_admin/README.md
- pt/django_forms/README.md
- pt/django_models/README.md
- pt/django_templates/README.md
- pt/django_urls/README.md
- pt/django_views/README.md
- pt/dynamic_data_in_templates/README.md
- pt/html/README.md
- pt/python_introduction/README.md
The good news: The Brazilian Portuguese is almost ready to go out :dancers: !
The bad news: I haven't been able to look over Gitbook as throughly as I'd like and there are some ladies who've worked very hard trying to get this ready to use at their Installfest tonight. At the very least, I know the light blue "tip" boxes aren't showing up. If anyone has a couple of minutes to put a second set of eyes on this, it would be very much appreciated. :bow:
> WIP-Portuguese-BR Beta!

- en/deploy/README.md
- pt/deploy/README.md
whitenoise had a major version number big change.
> updated django and whitenoise version numbers in "Deploy!" chapter.

- en/django_templates/README.md
Addresses issue [#419](https://github.com/DjangoGirls/tutorial/issues/419); this is more correct with what the changes actually were.
> Update example commit comment

- en/django_forms/README.md
Add escape tags to form.as_p because it's not showing up.
> Escape template tags

- en/django_installation/instructions.md
- en/django_models/README.md
- en/django_start_project/README.md
I've put a few more chapters through hemingwayapp to help improve the grammar and wording.
It's hard finding a balance between too many pull requests and too many file changes, so if you have a preference let me know :laughing:
> Django installation & models chapter through hemingwayapp

- en/deploy/README.md
> Put deploy! chapter through hemingwayapp

- en/django_templates/README.md
- en/django_urls/README.md
- en/django_views/README.md
> Put django urls, django view, and django templates chapter through hemingway

- en/django_forms/README.md
The published_date is clearly set, fixed documentation to follow code behavior.
> Fix paragraph regarding publish_date when creating post.

- en/installation/README.md
I pointed somebody at the install chapter page and they accidentally went too far and started working on the workshop chapters - I'm not sure it's clear when to stop! I hope this little section might help make that clearer. :)
> Installation page: tell people what to do next

- en/python_installation/instructions.md
Refs #474. Thanks @winterflower for the suggestion
> Noted that there's no need to upgrade from 3.4.0 to 3.4.3

- en/css/README.md
- en/django_installation/instructions.md
- en/django_models/README.md
- en/django_orm/README.md
Small grammar and clarity edits, especially around the use of commonly confused Latin abbreviations.
> grammar edit

- en/python_introduction/README.md
`participant` dict has a scrollbar on smaller screens
> prettyprint dict and fix method/function naming

- pt/deploy/README.md
Also added a full stop to break the sentence (which my limited grasp of Portuguese tells me is correct there :-)
> Corrected spelling of PythonAnywhere

- en/python_installation/instructions.md
To be more specific about adding Python to your Windows path. Issue #512
> Updated Python install instructions for Windows

- it/intro_to_command_line/README.md
> fix a few typos in italian version ch 3: intro to command line

- en/intro_to_command_line/README.md
I've had several issues where participants tried to input the prompt
itself. Therefore I suggest to make this point a bit more clearly. Also
In some places (I'll check later where) the tutorials (and their
translations) include much more of the prompt, which adds to the
confusion.
> Clarify the command line prompt

- en/python_introduction/README.md
The description of color-coding is before saving of the file. Color
coding doesn’t happen until the file is saved and the editor knows what
file type it is.
> Move color-coding commentary

- en/css/README.md
- en/django_models/README.md
Students new to computers sometimes were confused about what window to type things into.
> A couple of minor typos & clarification.

- it/SUMMARY.md
- it/code_editor/instructions.md
- it/css/README.md
- it/deploy/README.md
- it/django/README.md
- it/django_forms/README.md
- it/django_installation/instructions.md
- it/django_models/README.md
- it/django_orm/README.md
- it/django_start_project/README.md
- it/django_urls/README.md
- it/django_views/README.md
- it/dynamic_data_in_templates/README.md
- it/extend_your_application/README.md
- it/how_the_internet_works/README.md
- it/html/README.md
- it/python_installation/README.md
- it/python_installation/instructions.md
- it/python_introduction/README.md
- it/template_extending/README.md
This is a work in progress, we'll leave it open to sync our work with other contributors
> Fix typos for italian translation

- tr/deploy/README.md
- tr/django_admin/README.md
- tr/django_models/README.md
- tr/django_orm/README.md
- tr/django_start_project/README.md
- tr/django_urls/README.md
- tr/django_views/README.md
Turkish translation of the tutorial is done mostly with the help of a group of people who are not familiar with Django. This pull request includes the technical reading fixes and some typos with overall fixes.
> Fix typos for Turkish translation

- tr/code_editor/instructions.md
- tr/css/README.md
- tr/deploy/README.md
- tr/django_installation/instructions.md
- tr/django_models/README.md
- tr/django_orm/README.md
- tr/django_start_project/README.md
- tr/django_urls/README.md
- tr/django_views/README.md
- tr/html/README.md
- tr/installation/README.md
- tr/intro_to_command_line/README.md
- tr/python_installation/instructions.md
- tr/python_introduction/README.md
We still have important fixes that need to done before we go online with our event tomorrow.
It is the second part of proofreading of the tutorial for Turkish.
> Fix typos and grammar in Turkish translation - part 2

- it/python_introduction/README.md
> Fixed 'name' var translation

- it/python_introduction/README.md
> Fixed list length

- es/intro_to_command_line/README.md
> Fix command typo

- es/html/README.md
The command block for Spanish is missing new lines and the collectstatic.
> Fix code for Spanish version

- it/deploy/README.md
We have specified the version of Django to avoid the default version (1.9)
> add version to django and whitenoise

- tr/deploy/README.md
Virtualenv dizin yolu düzeltildi
> Update deploy page

- es/deploy/README.md
> Cambio mvenv por myvenv ya que al crear el virtualenv ese era el nombre

- book.json
This should fix the analytics not being recorded in Google Analytics (https://github.com/GitbookIO/plugin-ga/commits/master).
CC @patjouk
> Use latest version of ga plugin

- es/deploy/README.md
- `Pat on the back` expression was translated to Spanish exactly word-by-word.
- IMHO `Palmada en la espalda` is not quite common to say, a better generic translation would be `Buen Trabajo` meaning `Good Job` in English.
- Ref: http://www.wordreference.com/es/translation.asp?tranword=pat#enes:120275
> es - `pat on the back`

- es/django_forms/README.md
When user posted new stuff it wasn't published automatically due to the lack of a published date.
> Timezone bug

- ru/css/README.md
- ru/django_forms/README.md
- ru/django_orm/README.md
- ru/dynamic_data_in_templates/README.md
- ru/extend_your_application/README.md
- Added cyrillic Google font
- Fixed bunch of small syntax highlighting problems
> Small bugfixes in in Russian translation

- en/deploy/README.md
- en/django_forms/README.md
- en/django_models/README.md
- en/django_urls/README.md
- en/django_views/README.md
- en/dynamic_data_in_templates/README.md
- en/whats_next/README.md
Refer latest version of django used in the tutorial.
> Replace multiple occurrences of django 1.8 with 1.9 

- en/python_introduction/README.md
I saw two separate attendees type <their_name> including the greater than and less than.  Explicit!
> Be more specific about what to replace and how

- es/django_start_project/README.md
La forma en como estaba el texto no se entendia y quiza estuviera mal traducida.
> Cambio redaccion de nota para aclarar el uso de .

- fr/deploy/README.md
Adding a missing "/static" (line 47).
> Update Readme.md (french version)

- fr/css/README.md
Line 42 : we need to create a folder (dossier) called "static", not a file (fichier).
> Update Readme.md (french)

- es/django_start_project/README.md
Hola, creo que esa nota está en el párrafo incorrecto. Cree un pull request previo añadiendo otro párrafo que faltaba, pero ya veo que en esta parte no se ha hecho una traducción literal de cada párrafo. Por eso borré el anterio PR.
Saludos
> Nota sobre el punto '.' cambiada de sitio

- es/django_installation/README.md
Sorry for the last line added as changed. It hasn't been changed at all. Just the typo.
Cheers!
> Solved typo.

- en/django_forms/README.md
- en/extend_your_application/README.md
Use \d instead of [0-9], which is explained in chapter 13.
> Simplify regex

- pt/django_forms/README.md
Also fixed 'mport' to 'import' in line 97
> [pt] added missing published_date statement to post_new and post_edit

- fr/html/README.md
Replace ``template/blog/blog` -> `blog/template/blog`
> Wrong path (french tutorial)

- en/django_urls/README.md
- en/django_views/README.md
Fixes #686
I've moved the line that introduces comments into the next chapter, since I think that's where we now see them first.
I wonder if comments should be mentioned in Intro to Python though?
> Urls py changes

- en/django_urls/README.md
- en/django_views/README.md
> Amend wording around introduction of error messages and DEBUG error pages

- en/django_start_project/README.md
Include `admin` under `Operations to perform:` heading, screenshot here: https://i.imgur.com/9hQ6iYA.png
> Update output of python manage.py migrate

- en/django_start_project/README.md
Reverts DjangoGirls/tutorial#726
@ProProgrammer Can you thumb?
> Revert "Update output of python manage.py migrate"

- cs/README.md
- cs/css/README.md
- cs/deploy/README.md
- cs/django_forms/README.md
- cs/django_installation/instructions.md
- cs/django_models/README.md
- cs/django_start_project/README.md
- cs/django_urls/README.md
- cs/domain/README.md
- cs/python_installation/instructions.md
- cs/python_introduction/README.md
i hope i am not breaking the translation workflow by fixing the typos (and bit of grammar) here via github pull request - cc @tricoder42 
ps: thx everybody for all the hard work! authors of the text, translators, attendees, coaches ;))
> Simple czech fixes

- book.json
Hi DjangoGirls team! I've published version `3.0.0-pre.7` of GitBook which fix a few bugs for multilingual books, it'll also fix the download of PDF for the book.
:beers:
> Be less restrictive about the GitBook version

- it/django_installation/instructions.md
- it/django_start_project/README.md
Some errors found during DjangoGirls Florence 2016
> Italian translation fixes

- fr/deploy/README.md
Suppressing mentions of whitenoise.
Adding new mentions about CSS & static handling.
Adding new comments.
Fixed typo.
> Bringing deploy up to speed in french

- fr/django_forms/README.md
Correct formatting of code (fr/django_forms)
> Correct formatting of code (fr/django_forms)

- en/django_installation/instructions.md
See mentions of accented characters in later part of the tutorial:
since having accented chars in the directory name will cause problems
later on on windows, we should make sure students won't need to
start again with a good directory name.
> warn at the earliest opportunity about issues caused by accented chars

- es/extend_your_application/README.md
Hi there, I was couch at the DjangogirlsCUU and while the girls were following the tutorial I notice that there was a broken image, so I fixed it.
> Fix broken image and add python highlight to a block

- it/django_forms/README.md
form is translated as "il form" in all other occurences, also "la forma" does not make sense in this context :)
> it: fix "la forma" vs "il form"

- cs/dynamic_data_in_templates/README.md
- cs/extend_your_application/README.md
- cs/html/README.md
Wrong -Co je to šablona, se ami ptáš?
Right +Co je to šablona, se asi ptáš?
> cs: Typo = ami - asi

- en/README.md
> Fix README typo: 'ecourage' --> 'encourage'

- en/django_templates/README.md
URL specified does not work. 
Should be https://yourname.pythonanywhere.com/admin
> Removed www from pythonanwhere admin url

- pt/README.md
- pt/django/README.md
- pt/django_installation/README.md
- pt/python_installation/README.md
- pt/python_introduction/README.md
Fixing a typo and a path that doesn't exist anymore
> Minor fixes in pt translation

- pl/django_orm/README.md
> Fix code snippet in PL version

- en/django_start_project/README.md
once you've seen the "It worked!" page.
> It's okay to stop the web server

- en/code_editor/README.md
- en/code_editor/instructions.md
- en/how_the_internet_works/README.md
- en/intro_to_command_line/README.md
- en/python_installation/README.md
- en/python_introduction/README.md
This pull request includes copy-editing for English language usage (fixing grammar, punctuation, and idiomatic language) for pages up to and including "Introduction to Python".
> Copy-editing up to and including Introduction to Python.

- en/chromebook_setup/README.md
- en/chromebook_setup/instructions.md
- en/code_editor/README.md
- en/css/README.md
- en/django_installation/README.md
- en/django_start_project/README.md
- en/installation/README.md
- en/python_installation/README.md
This PR adds information on doing the tutorial on a Chromebook using the Cloud 9 editor/VM instead of a local machine.
I'm new to gitbook so apologies in advance if there are any markdown issues. I did QA the links I added.
I used these instructions to do the entire tutorial, so I'm pretty confident in their correctness.
> Chromebook Support

- pt/django_forms/README.md
> Fixing URL

- en/deploy/README.md
- en/python_installation/instructions.md
- en/python_introduction/README.md
This brings us up to date in the installation and deployment sections too.
> Update remaining Python 3.4 references in the english version to 3.5.

- en/django_forms/README.md
- en/extend_your_application/README.md
This import is never used in thoose files.
> Removed unused imports of django.conf.urls.include

- cs/django_forms/README.md
- cs/extend_your_application/README.md
- es/django_forms/README.md
- es/extend_your_application/README.md
- fr/django_forms/README.md
- fr/extend_your_application/README.md
- hu/django_forms/README.md
- hu/extend_your_application/README.md
- it/django_forms/README.md
- it/extend_your_application/README.md
- ko/django_forms/README.md
- ko/extend_your_application/README.md
- pl/django_forms/README.md
- pl/extend_your_application/README.md
- pt/django_forms/README.md
- pt/extend_your_application/README.md
- ru/django_forms/README.md
- ru/extend_your_application/README.md
- sk/django_forms/README.md
- sk/extend_your_application/README.md
- tr/django_forms/README.md
- tr/extend_your_application/README.md
- uk/django_forms/README.md
- uk/extend_your_application/README.md
- zh/django_forms/README.md
- zh/extend_your_application/README.md
same as my last pull request :)
> translations: removed unused import of django.conf.urls.include

- en/django_installation/instructions.md
> Add instructions to upgrade pip

- en/intro_to_command_line/README.md
> introduction to commandline: Rename folder into 'practice' again

- cs/python_installation/instructions.md
hyphen-minus instead of ndash in `--version`
> instructions.md: --version without ndash

- en/django_models/README.md
This is a list using square brackets in my settings.py file
> Update django-models text

- cs/django_start_project/README.md
Thanks for help @Miro Hrončok :)
> Czech proofreading

- pt/django_installation/README.md
Changing a stretch to give a better sense, according to the original English version.
> pt: Update README.md to give a better sense

- pt/extend_your_application/README.md
Was missing translate the word 'thing' in the sentence.
> Adding a word that was missing in the translation.

- en/intro_to_command_line/README.md
Came across this when going through the tutorial with my team :smile:
> Fix backslash -> slash

- en/README.md
- Update Gitter badge URL format -- [_Beautiful is better than ugly._](https://www.python.org/dev/peps/pep-0020/#id3) :heart_eyes: 
- Remove tracking data (query string) from Gitter badge link -- [_Now is better than never._](https://www.python.org/dev/peps/pep-0020/#id3) _... to remove tracking._  :smirk: 
- Make word wrapping a bit nicer in licensing paragraph. -- [_Readability counts._](https://www.python.org/dev/peps/pep-0020/#id3) :relieved:
> Gitter badge: update linke and remove tracking

- en/intro_to_command_line/README.md
- pl/intro_to_command_line/README.md
* rmdir on windows deletes directories
* missing rmdir /S in PL tutorial
> Intro to command line fixed

- hu/python_introduction/README.md
Correct sample code in If...elif...else section
> Correct sample code in If...elif...else section

- en/django_start_project/README.md
This was an issue several people ran in to during the last conference. There is probably a better fix for this but this one is simple and can be done quickly without distracting from the rest of the tutorial.
> Fixed bug with allowed hosts.

- en/deploy/README.md
Changed: The default page for your site should say "Welcome to Django!"
To: The default page for your site should say "It worked!"
> Matching welcoming texts

- en/deploy/README.md
- en/django_models/README.md
- en/django_urls/README.md
- en/dynamic_data_in_templates/README.md
- en/python_introduction/README.md
While going through the tutorial with a few mentees, I spotted a few minor issues. Lets fix them up.
> Fix grammar and tyops

- pl/README.md
- pl/SUMMARY.md
- pl/css/README.md
- pl/deploy/README.md
- pl/django/README.md
- pl/django_admin/README.md
- pl/django_forms/README.md
- pl/django_installation/instructions.md
- pl/django_models/README.md
- pl/django_orm/README.md
- pl/django_start_project/README.md
- pl/django_templates/README.md
- pl/django_urls/README.md
- pl/django_views/README.md
- pl/dynamic_data_in_templates/README.md
- pl/extend_your_application/README.md
- pl/how_the_internet_works/README.md
- pl/html/README.md
- pl/installation/README.md
- pl/intro_to_command_line/README.md
- pl/python_installation/instructions.md
- pl/python_introduction/README.md
- pl/template_extending/README.md
- pl/whats_next/README.md
Mainly fixes of linguistic errors. Some updates in links. Adding Polish strings where possible. Few formatting fixes.
> Polish tutorial fixes

- cs/python_introduction/README.md
- en/python_introduction/README.md
- es/python_introduction/README.md
- fr/python_introduction/README.md
- hu/python_introduction/README.md
- it/python_introduction/README.md
- ko/python_introduction/README.md
- pl/python_introduction/README.md
- pt/python_introduction/README.md
- ru/python_introduction/README.md
- sk/python_introduction/README.md
- uk/python_introduction/README.md
- zh/python_introduction/README.md
This allows copy-pasting and doesn't require knowing the username.
Note that I don't know if there's a Windows equivalent. There may also be a better wording of the paragraph.
> Use ~ rather than /home/<your_name>

- en/extend_your_application/README.md
When I walked through the tutorial, I got hung up on where post.pk came from and, later, bugs introduced by renaming the pk variable in the URL pattern without also changing the variable name in the template link and view function – which isn't made explicit in the tutorial. These edits clarify/rectify where I went wrong!
> clarify where primary key comes from & how to reference it

- cs/python_introduction/README.md
- en/python_introduction/README.md
- es/python_introduction/README.md
- fr/python_introduction/README.md
- hu/python_introduction/README.md
- it/python_introduction/README.md
- ko/python_introduction/README.md
- pl/python_introduction/README.md
- pt/python_introduction/README.md
- ru/python_introduction/README.md
- sk/python_introduction/README.md
- uk/python_introduction/README.md
- zh/python_introduction/README.md
This is the windows version of a7f5e56c03168f2e68164b95961c9d15d6d108be. By using a variable users can copy paste and don't have to figure out their username.
As stated in https://github.com/DjangoGirls/tutorial/pull/904#issuecomment-266379543 I don't have a Windows install to verify this works. This Thursday I'm going to a follow up meetup where I might have the chance to test this.
> Use %HomePath% instead of C:\Users\<your_name>

- README.md
> gitbook.io no longer exists

- es/README.md
It's just a typo error, "inclusos" for "incluso"
> inclusos for incluso

- en/README.md
The version "feel somehow left behind" has a strong negative feeling to it. To me (as a coach) this feels problematic/counterproductive when starting off the day with super motivated participants (essentially, I'm "reminding" them about the "fact" that they might be "left behind" instead of, e.g., "courageous" or "engaged"). 
I'm proposing a small correction to soften this feel. However, ideally, I would prefer the tutorial to start off with a friendly and warm welcome (and potentially congratulations that the participant worked up the courage to get herself into this in the first place). Maybe add a dedicated "Welcome" section?
> A more positive feel for the "Introduction"

- en/python_introduction/README.md
added drop downs for OSX Linux and Windows in the Save it! section.
> added drop downs

- en/deploy/README.md
Right now, https://pythonanywhere.com/ is timing out but https://www.pythonanywhere.com/ is working.
> PythonAnywhere sometimes gets weird without www

- en/django_models/README.md
Coming from the command line, participants keep forgetting to save their edits and keep getting lots of errors. Just a small reminder.
> Reminder to save files

- en/README.md
First draft, comments welcome!
> Welcome to tutorial section

- en/python_introduction/README.md
Hi,
Great tutorial! thanks for your work :)
There were just some missing command line result. This can be strange for someone which doesn't know the command lines to have a different result than the tutorial.
> Add missing command line results

- cs/installation/README.md
- fr/installation/README.md
- it/installation/README.md
- ko/installation/README.md
- pl/installation/README.md
- sk/installation/README.md
- tr/installation/README.md
- zh/installation/README.md
Fixes #998.
Actually present in several languages sections, this should update them "all" (except some which had been corrected already, and some others which do not have an installation README).
> Correct link at the end of "Installation" page

- cs/django_templates/README.md
- en/django_templates/README.md
- fr/django_templates/README.md
- sk/django_templates/README.md
- tr/django_templates/README.md
The above screenshot (images/step1.png) still needs to be updated, but I don't have an env right now.
> Use Django 1.10 queryset repr

- pt/deploy/README.md
Replaced 'PythinAnywhere' with 'PythonAnywhere'
> Fixed typo in pt_BR translation

- en/django_start_project/README.md
Caused confusion in workshop, participants suggested adding a note
> Short note how/why to open files in code editor

- pt/python_introduction/README.md
> [Portuguese] Update README.md

- hu/deploy/README.md
- hu/deploy/install_git.md
- hu/django_admin/README.md
- hu/django_installation/instructions.md
- hu/django_models/README.md
- hu/django_start_project/README.md
- hu/how_the_internet_works/README.md
- hu/intro_to_command_line/README.md
- hu/python_installation/instructions.md
- hu/python_introduction/README.md
update up to 'Deploy!' chapter, except python and django installation chapters
(note: updates of other chapters still forthcoming)
> Update hungarian translation due to changes in english tutorial

- hu/css/README.md
- hu/deploy/README.md
- hu/deploy/install_git.md
- hu/django_forms/README.md
- hu/django_installation/instructions.md
- hu/django_models/README.md
- hu/django_templates/README.md
- hu/django_urls/README.md
- hu/django_views/README.md
- hu/dynamic_data_in_templates/README.md
- hu/extend_your_application/README.md
- hu/html/README.md
- hu/intro_to_command_line/README.md
- hu/python_installation/instructions.md
- hu/python_introduction/README.md
- hu/whats_next/README.md
this should complete translation review, all chapters are up-to-date (some cosmetic differences remain in markup, etc.)
> [Hungarian] further updates to hungarian translation

- es/django_forms/README.md
We found an issue with that could prove detrimental to the progress of our event. We've found a fix and are pushing it in case it pops up for someone else.
> Adding a error handling solution in Forms spanish section

- ko/deploy/install_git.md
Fix description what we should choose when install git in windows.
> [Korean] Fix description

- en/django_start_project/README.md
We just made the tutorial on windows an linux in parallel and noticed the command did not work.
> Windows10 error

- zh/css/README.md
> [zh] Update README.md

- fr/django_urls/README.md
- fr/django_views/README.md
"Translation" of 9d03b12 in French.
> fr/Update urls chapter for Django >= 1.9

- pt/README.md
- pt/how_the_internet_works/README.md
- pt/intro_to_command_line/README.md
- pt/python_installation/README.md
#1088 
Improves the language to a more inclusive one, assuming that the reader won't be a male and admitting that the mentor helping them might be either a male or a female (as opposed as it is now, where mentors are always identified as males).
I'm experimenting with a new tag, that's already used in the English tutorial, to collapse instructions for each OS.
I've also changed the Python installation instructions to get it more up to date. I've chosen to keep Python 3.4 as the version to be used because it's the latest one can get on Ubuntu as of now and I believe it wouldn't be ideal if Windows and Linux users used different Python versions during the workshop.
> [Portuguese] Improves the language and visual guides for each OS.

- en/django_start_project/README.md
Adding some text for the language code variable.
> Explain the LANGUAGE_CODE

- zh/django_admin/README.md
> [Simplified Chinese] Fixed a typo

- .travis.yml
- added .travis.yml file for automatic builds and errors detection at the PR states.
> Add .travis config file for automatic builds

- pt/django_urls/README.md
> Fixed typos, removed line in english

- pt/python_introduction/README.md
- Fix python command in pt documentation
> Fix bug in dictionary

- pt/code_editor/instructions.md
- Added VS Code to Code Editor list
- Fixed bold formatting on 'texto sem formatação'
> Added VS Code to the Code Editor list

- pt/README.md
- pt/domain/README.md
- Added volunteers and put in order
- Translated a paragraph from introduction
> Added volunteers and translated a paragraph from introduction

- pt/how_the_internet_works/README.md
- pt/intro_to_command_line/README.md
- bug fix in the Female text 
- translation of tests
- other little fixes bug in the translation
> Reviewed translation pt-br

- pt/django/README.md
Exclusão de um "é" que estava sobrando na frase.
-
-
-
> Pequena correção ortográfica.

- en/README.md
- en/code_editor/instructions.md
- en/css/README.md
- en/deploy/README.md
- en/django_forms/README.md
- en/django_installation/instructions.md
- en/django_orm/README.md
- en/django_start_project/README.md
- en/django_templates/README.md
- en/how_the_internet_works/README.md
- en/html/README.md
- en/intro_to_command_line/README.md
- en/python_installation/README.md
- en/python_introduction/README.md
-Addressing this issue - https://github.com/DjangoGirls/tutorial/issues/729
> removed instances of the words 'easy', 'simple' and 'fast'

- en/django_urls/README.md
A lot of my students miss this import. It's very subtle. This isn't as pretty but more obvious (as suggested by @thibaudcolas).
Closes GH-1165
> Make the import include clearer

- en/django_views/README.md
Add an argument of `{}` to the `render()` call in the `django_views` portion of the tutorial, to match up to the code referenced in the `dynamic_data_in_templates` portion.
> [English]: Issue #1179 Match view code

- en/deploy/signup_pythonanywhere.md
> grammar error - deploy

- en/django_installation/instructions.md
- punctuation error - line number 15, 17
- Articles error - line number 59
> grammar error - django_installation

- en/python_installation/instructions.md
- punctuation-error on line number 12 and 79.
> punctuation-error - python installation

- en/django_start_project/README.md
- proper extension for `django-admin.exe`
- fix for missing \` at the beginning of code segment
> Fixing formatting issue + proper django-admin extension for Windows

- de/html/README.md
should fix the issue https://github.com/DjangoGirls/tutorial/issues/1149
this should change replaces the broken lines with the matching lines from the English version.
> fix the code lines at the end

- hu/deploy/README.md
- hu/python_introduction/README.md
- fix formatting in python_introduction
- fix typo in deploy
> Minor fixes for hungarian instructions

- en/chromebook_setup/instructions.md
- Indefinite Articles error - line number 8
- typo - line number 30
> Indefinite Articles error and typo in chromebook_setup/instructions.md

- de/django_installation/instructions.md
- de/installation/README.md
- de/python_installation/instructions.md
- de/python_introduction/README.md
- Added panels according to English and Polish translation files.
- Corrected the link for including the git install chapter.
- Corrected typos
Fix for issue [#1148](https://github.com/DjangoGirls/tutorial/issues/1148)
> [German]: Issue#1148 Add collapsible panels

- en/html/README.md
- fixed grammatical mistakes on-line number: 5, 33, 141, 164.
> HTML - fixed grammatical mistakes

- en/django_urls/README.md
Fixes:
- Grammatical mistakes in line number 11, 36, 43, 47, 63, 65, 91, 125.
> django_urls fixed grammatical mistakes

- en/deploy/README.md
for consistency with other examples.  Plus ola is a nicer username than hjwp...
> Use ola as username in example git command output instead of hjwp

- en/deploy/README.md
otherwise there are two section headings saying "you are live!"
> change a duplicated section heading

- en/deploy/README.md
Someone posted a [question](https://www.pythonanywhere.com/forums/topic/4440/#id_post_47683) in the PythonAnywhere forums about this -- they had failed to actually commit all the right files into git and push them up to github.
hopefully this will be a useful pointer if anyone else runs into the same issue!
> Add debugging tip re: missing settings file.

- pt/code_editor/instructions.md
- pt/python_installation/instructions.md
- pt/python_introduction/README.md
> reviewed translation pt

- en/extend_your_application/README.md
- en/python_introduction/README.md
> Include a warning icon before blocks that return errors

- en/django_orm/README.md
- en/django_templates/README.md
This continues work done in 7eb1e07
I have only done this for English, I can probably do a followup commit with changes to other languages if desired, but am not 100% if that would be the right process.
And also fixes one little quoting syntax issue
> Change more output samples to current QuerySet output

- pt/code_editor/README.md
- pt/code_editor/instructions.md
- pt/django/README.md
- pt/django_installation/instructions.md
- pt/intro_to_command_line/README.md
- pt/python_installation/README.md
- pt/python_installation/instructions.md
- pt/python_introduction/README.md
I did some small fixes in the language (we are talking to women who read this tutorial during the workshop, so why the mentions to programmers and hackers and such should be the male version in portuguese?) and removed some text that was repeated.
> Small fixes for pt-br version

- de/django_installation/instructions.md
- en/django_installation/instructions.md
- hu/django_installation/instructions.md
- ko/django_installation/instructions.md
- pl/django_installation/instructions.md
- pt/django_installation/instructions.md
- ru/django_installation/instructions.md
- sk/django_installation/instructions.md
- tr/django_installation/instructions.md
- Update `pip install` command to support all OS (it had a problem with the previous command on Windows).
> Update pip command for all OS

- en/python_introduction/README.md
Fixes #1257
- Make the indentation instructions more clear
- Add note about text editor setup (it might be misleading to say Tab = 4 spaces on every text editor)
What do you guys think?
> Make the indentation instructions more clear

- en/django_start_project/README.md
It's not needed to change the language code. This rephrases the text to
indicate it's optional. It also capitalizes languages and countries.
> Rephrase the LANGUAGE_CODE text

- en/deploy/README.md
to better fit the image as it looks since 7e173e2eea228c37ec9e1abb7eb26947d988512f:
[![](https://raw.githubusercontent.com/DjangoGirls/tutorial/7e173e2eea228c37ec9e1abb7eb26947d988512f/en/deploy/images/pythonanywhere_bash_console.png)](https://github.com/DjangoGirls/tutorial/commit/7e173e2eea228c37ec9e1abb7eb26947d988512f?short_path=c0f486d#diff-c0f486d8beca981db0c0f449a5e4b23d)
> Change image "alt" text for pythonanywhere_bash_console.png

- pt/css/README.md
- pt/django_forms/README.md
- pt/domain/README.md
- pt/extend_your_application/README.md
- pt/template_extending/README.md
- Fix words
- Translate topic in extends your application
- Fix syntax
> [pt] Fix some words

- tr/chromebook_setup/README.md
- tr/chromebook_setup/instructions.md
- tr/code_editor/instructions.md
- tr/css/README.md
- tr/deploy/README.md
- tr/deploy/install_git.md
- tr/deploy/signup_pythonanywhere.md
- tr/django/README.md
- tr/django_admin/README.md
- tr/django_forms/README.md
- tr/django_installation/instructions.md
- tr/django_models/README.md
- tr/django_orm/README.md
- tr/django_start_project/README.md
- tr/django_templates/README.md
- tr/django_urls/README.md
- tr/extend_your_application/README.md
- tr/html/README.md
- tr/intro_to_command_line/README.md
- tr/python_installation/instructions.md
- tr/python_introduction/README.md
- tr/template_extending/README.md
- tr/whats_next/README.md
Updates made by:
* uskudarli (https://crowdin.com/profile/uskudarli)
* Gökçe Uludoğan (https://crowdin.com/profile/gokceuludogan)
* nisanderman (https://crowdin.com/profile/nisanderman)
* Buğra İşgüzar (https://crowdin.com/profile/biisguzar)
* soulianis (https://crowdin.com/profile/soulianis)
LIving book available here: https://magul.gitbooks.io/django-girls-tutorial/content/v/359ab01b512f55c39acb5e2c4954b7e2832e1a80/
> Turkish current translation from Crowdin

- en/deploy/README.md
- en/django_start_project/README.md
- add `requirements.txt` in the result of `git status` command.
- add `requirements.txt` in the command line screen in bash console of pythonanywhere.
> Fixes #1308, add requirements.txt to the list of files

- en/django_models/README.md
It seems the output of this command has been changed recently. I deleted a line that no longer appears.
> Fix manage.py migrate output text

- en/deploy/signup_pythonanywhere.md
> Fix broken image and typo

- en/django_models/README.md
I added requirements.txt in the directory contents.
fixes #1348
> Fix the directories and files in Django models chapters

- en/django_urls/README.md
> Clarify instructions on URLs

- en/css/README.md
- en/django_admin/README.md
- en/django_forms/README.md
- en/django_models/README.md
- en/django_templates/README.md
- en/django_urls/README.md
- en/django_views/README.md
- en/dynamic_data_in_templates/README.md
- en/extend_your_application/README.md
- en/html/README.md
- en/template_extending/README.md
> Explicitly say to open files in code editor

- pt/django_start_project/README.md
- fixed a little expression from 'por acidentalmente' to 'acidentalmente'
> Fixed a littlet expression

- de/python_installation/instructions.md
* Raphael Das Gupta (https://crowdin.com/profile/das-g)
> German translation improvements from Crowdin made by:

- en/deploy/README.md
> Clarify extension on .gitignore

- en/deploy/README.md
> Clarify GitHub push

- tr/README.md
- tr/SUMMARY.md
- tr/chromebook_setup/instructions.md
- tr/code_editor/instructions.md
- tr/css/README.md
- tr/deploy/README.md
- tr/deploy/signup_pythonanywhere.md
- tr/django/README.md
- tr/django_admin/README.md
- tr/django_forms/README.md
- tr/django_installation/README.md
- tr/django_installation/instructions.md
- tr/django_models/README.md
- tr/django_orm/README.md
- tr/django_start_project/README.md
- tr/django_templates/README.md
- tr/django_urls/README.md
- tr/django_views/README.md
- tr/dynamic_data_in_templates/README.md
- tr/extend_your_application/README.md
- tr/how_the_internet_works/README.md
- tr/html/README.md
- tr/installation/README.md
- tr/intro_to_command_line/README.md
- tr/python_installation/instructions.md
- tr/python_introduction/README.md
- tr/template_extending/README.md
- tr/whats_next/README.md
* Berat Doğan (https://crowdin.com/profile/beratdogan)
* Çağıl (https://crowdin.com/profile/cgl)
* Gökçe Uludoğan (https://crowdin.com/profile/gokceuludogan)
* halime (https://crowdin.com/profile/halime)
* ozgunasli (https://crowdin.com/profile/ozgunasli)
* Sirin Saygili (https://crowdin.com/profile/saygilin)
* uskudarli (https://crowdin.com/profile/uskudarli)
> Turkish translation improvements made by:

- pl/chromebook_setup/instructions.md
- pl/code_editor/instructions.md
- pl/css/README.md
- pl/deploy/README.md
- pl/deploy/signup_pythonanywhere.md
- pl/django_admin/README.md
- pl/django_forms/README.md
- pl/django_models/README.md
- pl/django_start_project/README.md
- pl/django_templates/README.md
- pl/django_urls/README.md
- pl/django_views/README.md
- pl/dynamic_data_in_templates/README.md
- pl/extend_your_application/README.md
- pl/html/README.md
- pl/python_installation/instructions.md
- pl/template_extending/README.md
* Daga (https://crowdin.com/profile/dagaaaaa)
* Monika Czerniawska (https://crowdin.com/profile/wrozda)
* Zuzzka (https://crowdin.com/profile/Zuzzka)
CC: @Zuzzka, @wrozda, @dagaaaaa
> Polish translation improvement from Crowdin made by:

- en/chromebook_setup/instructions.md
> Fixing a typo

- en/django_start_project/README.md
Fixes #1385
The attendee who found this paragraph confusing thinks this proposed paragraph is clearer...
> Clarify command window running server

- en/deploy/README.md
- en/deploy/signup_pythonanywhere.md
- en/installation/README.md
Add notes to remember your password for GitHub and PythonAnywhere. See #1029.
> Add reminder about passwords for GitHub and PythonAnywhere

- en/code_editor/README.md
- en/python_introduction/README.md
> Expand on Chromebook note for code editor

- en/django_start_project/README.md
> Fix chromebook cloud9 web server instructions

- en/django_installation/instructions.md
connects to https://github.com/DjangoGirls/tutorial/issues/1368
> add detail to instructions for requirements.txt 

- en/django_admin/README.md
> Use ola as sample admin user name

- en/python_introduction/README.md
A lot of students are unsure whether they should replace the content so they often just add to it. This change is intended to assure students that they can safely remove it.
I'm not sure this is the best phrasing. Suggestions welcome.
> Explicitly suggest to replace the content

- en/django_urls/README.md
The example code of what to expect in your mysite/urls.py file erroneously included the include import,
This change fixes that and updates the reference below to explicitly mention which line to add the include to.
> correct expected code regarding include function

- el/django_urls/README.md
- el/extend_your_application/README.md
* Nick Mavrakis (https://crowdin.com/profile/manikos)
> Greek translation improvements from Crowdin made by:

- en/whats_next/README.md
Hello, I am the teacher of the Python for Everybody Specialization on Coursera.  As you mention, the course is not exactly free because they put the assessments behind a paywall.   I have a 100% free and 100% open version of the entire specialization on my own www.py4e.com we site - you can do all the quizzes, the auto-graded assignments, and peer graded assignments for free on my site.
-
-
-
> Add link to www.py4e.com

- en/deploy/signup_pythonanywhere.md
Originally spotted here: https://crowdin.com/translate/django-girls-tutorial/298/en-es#11681
> Fix multiple articles for "account" noun.

- en/installation/README.md
> Add brief command line info to installation page

- en/css/README.md
> Fix CSS selector

- en/extend_your_application/README.md
- fixed ellipsis
Motivation:
- an ellipsis in English requires 3 dots
> fix ellipsis

- ko/css/README.md
- Previously it was translated as 'loading *dynamic* data', which was supposed to be 'loading *static* data'.
> fixed a minor translation mistake

- en/django_forms/README.md
- en/django_templates/README.md
- en/extend_your_application/README.md
- en/html/README.md
> Fix up PythonAnywhere cd instructions

- LANGS.md
> Use Brazil flag for Brazilian Portoguese

- ja/python_introduction/README.md
Because other chpater names are in Japanese.
> Convert English chapter name to Japanese

- es/django_start_project/README.md
> Fixes ALLOWED_HOSTS sample.

- en/python_installation/instructions.md
I added the text for the Anaconda user to the "Python Installation" chapter.
I followed the comments on this PR #1519 .
Thank you.
> Add text for those who have installed Anaconda

- en/code_editor/instructions.md
Add Visual Studio Code as a text editor. I think, it is the most familiar code editor for beginners.
> [en] Code Editor - add Visual Studio Code

- en/how_the_internet_works/README.md
- join two adjacent sentences
- add a comma in another sentence
> Improve grammar

- pt/chromebook_setup/README.md
- pt/chromebook_setup/instructions.md
- pt/code_editor/README.md
- pt/code_editor/instructions.md
- pt/css/README.md
- pt/deploy/README.md
- pt/deploy/install_git.md
- pt/deploy/signup_pythonanywhere.md
- pt/django/README.md
- pt/django_admin/README.md
- pt/django_forms/README.md
- pt/django_installation/instructions.md
- pt/django_models/README.md
- pt/django_orm/README.md
- pt/django_start_project/README.md
- pt/django_templates/README.md
- pt/django_urls/README.md
- pt/django_views/README.md
- pt/extend_your_application/README.md
- pt/how_the_internet_works/README.md
- pt/html/README.md
- pt/installation/README.md
- pt/intro_to_command_line/README.md
- pt/intro_to_command_line/open_instructions.md
- pt/python_installation/README.md
- pt/python_installation/instructions.md
- pt/python_introduction/README.md
- pt/template_extending/README.md
- pt/whats_next/README.md
* beambrosio (https://crowdin.com/profile/beambrosio)
* Carolina Carvalho Gontijo (https://crowdin.com/profile/ninacalorina)
* Dani Andrade (https://crowdin.com/profile/danyelebatista)
* Danilo Venticinque (https://crowdin.com/profile/danilosoares)
* Emanoel Lopes (https://crowdin.com/profile/emanoelopes)
* EsthvnFerrtn (https://crowdin.com/profile/EsthvnFerrtn)
* gabrielheming (https://crowdin.com/profile/gabrielheming)
* Geysa Priscila (https://crowdin.com/profile/geysapriscilasz)
* Guilherme Abraham (https://crowdin.com/profile/guilherme.abraham93)
* Isabela Nascimento (https://crowdin.com/profile/belaanascimento)
* Julio A. (https://crowdin.com/profile/itsnothulio)
* Lais Garcia (https://crowdin.com/profile/laisgarcia3009)
* Luís Henrique Puhl De Souza …
> Portuguese (Brazilian) improvements by:

- es/template_extending/README.md
> Fixed spelling

- pt/intro_to_command_line/open_instructions.md
* Sara Coutinho (https://crowdin.com/profile/sarabandeira14)
* vasques96 (https://crowdin.com/profile/vasques96)
> Portuguese (Brazilian) translation improvements by:

- pl/django_admin/README.md
- fix broken link for django admin panel
> fix: broken link for django admin panel

- pl/django_start_project/README.md
- change lang code in polish settings.py
> set lang code in Polish tutorial to Polish (Poland)

- en/intro_to_command_line/README.md
Code before this commit looks like a paste-o
> Fix "Command Help: Windows" section title

- pl/css/README.md
- change h1 to h2 in selectors for polish
> fix: change h1 to h2 in selectors for polish

- pl/python_introduction/README.md
- rename lottery to polish equivalent
> fix: rename lottery to polish equivalent

- sk/intro_to_command_line/README.md
> sk/intro_to_command_line - fix exit command int overview table

- sk/python_introduction/README.md
> sk/python_introduction - translation

- en/chromebook_setup/instructions.md
This is a PR based on #1265 and I created it to let CI run the build against it.
> Update Cloud9 instructions

- en/deploy/README.md
- In the deploy chapter, images were written in html img tags. Fixed to markdown.
> Fix html img tag to markdown

- es/README.md
- es/SUMMARY.md
- es/chromebook_setup/instructions.md
- es/code_editor/README.md
- es/code_editor/instructions.md
- es/css/README.md
- es/deploy/README.md
- es/deploy/install_git.md
- es/deploy/signup_pythonanywhere.md
- es/django_admin/README.md
- es/django_forms/README.md
- es/django_installation/instructions.md
- es/django_models/README.md
- es/django_orm/README.md
- es/django_start_project/README.md
- es/django_templates/README.md
- es/django_urls/README.md
- es/django_views/README.md
- es/dynamic_data_in_templates/README.md
- es/extend_your_application/README.md
- es/how_the_internet_works/README.md
- es/html/README.md
- es/installation/README.md
- es/intro_to_command_line/README.md
- es/intro_to_command_line/open_instructions.md
- es/python_installation/instructions.md
- es/python_introduction/README.md
- es/template_extending/README.md
- es/whats_next/README.md
* Alberto Gómez Herrera (https://crowdin.com/profile/MirageIonova)
* andreagaredine (https://crowdin.com/profile/andreagaredine)
* Angelica (https://crowdin.com/profile/ALandazabal)
* Anna Branco (https://crowdin.com/profile/annabranco)
* Anna Warzecha (vi) (https://crowdin.com/profile/aniav)
* FABIO MORALES (https://crowdin.com/profile/fmorales100)
* Francisco Javier (https://crowdin.com/profile/xiscodroid)
* Gerardo Lopez Dueñas (https://crowdin.com/profile/gerardolopezduenas)
* gerlyn (https://crowdin.com/profile/gerlyn)
* Javier Abadía (https://crowdin.com/profile/javier.abadia)
* Juan Alvarez (https://crowdin.com/profile/juan.m.alvarez)
* Kevin Harper (https://crowdin.com/profile/khdc-me)
* Laura Vargas Gastélum (https://crowdin.com/profile/laura.vargas)
* Leonardo J. Caballero G. …
> Spanish translation improvements from Crowdin made by:

- en/deploy/README.md
Update line 61: 'Initial commit' for 'No commits yet'
> DjangoGirls#1570

- tr/css/README.md
> Turkish typo fix

- en/code_editor/instructions.md
I modified the download URL for VSCode.
I think this URL is simpler to download.
Thank you.
> Fix download url of VSCode

- it/extend_your_application/README.md
> Fix typo in Italian translation of deployment section of "Extend your application" chapter

- cs/django_forms/README.md
- de/django_forms/README.md
- el/django_forms/README.md
- en/django_forms/README.md
- es/django_forms/README.md
- fa/django_forms/README.md
- fr/django_forms/README.md
- hu/django_forms/README.md
- it/django_forms/README.md
- ja/django_forms/README.md
- ko/django_forms/README.md
- pl/django_forms/README.md
- pt/django_forms/README.md
- ru/django_forms/README.md
- sk/django_forms/README.md
- tr/django_forms/README.md
- uk/django_forms/README.md
- zh/django_forms/README.md
Reverts DjangoGirls/tutorial#1589
See https://github.com/DjangoGirls/tutorial/pull/1589#pullrequestreview-300581137
> Revert "Fixed small typo in div name"

- es/README.md
- es/chromebook_setup/instructions.md
- es/code_editor/README.md
- es/code_editor/instructions.md
- es/css/README.md
- es/deploy/README.md
- es/deploy/signup_pythonanywhere.md
- es/django/README.md
- es/django_admin/README.md
- es/django_forms/README.md
- es/django_installation/instructions.md
- es/django_models/README.md
- es/django_orm/README.md
- es/django_start_project/README.md
- es/django_templates/README.md
- es/django_urls/README.md
- es/django_views/README.md
- es/dynamic_data_in_templates/README.md
- es/extend_your_application/README.md
- es/how_the_internet_works/README.md
- es/html/README.md
- es/installation/README.md
- es/intro_to_command_line/README.md
- es/python_installation/instructions.md
- es/python_introduction/README.md
- es/template_extending/README.md
- es/whats_next/README.md
- Spelling mistakes
- Puntuaction mistakes
- Style improved
> Spelling and style mistakes corrected

- de/django_installation/instructions.md
- en/django_installation/instructions.md
- es/django_installation/instructions.md
- fa/django_installation/instructions.md
- fr/django_installation/instructions.md
- ja/django_installation/instructions.md
- pt/django_installation/instructions.md
- Updated the django installation section to fix issue #1592 for the languages that had this (de, en, es, fa, fr, ja, pt)
fixes #1592
> Move note about activating virtual env into relevant section

- fr/SUMMARY.md
- fr/code_editor/instructions.md
- fr/django_forms/README.md
- fr/django_installation/instructions.md
- fr/django_models/README.md
- fr/django_start_project/README.md
* Raphael Das Gupta (https://crowdin.com/profile/das-g)
> French translation improvements from Crowdin made by:

- en/deploy/README.md
- Add vscode directory to gitignore (English version)
closes #1576
> Add vscode directory to gitignore

- fa/deploy/README.md
- fa/extend_your_application/README.md
* rahimz (https://crowdin.com/profile/rahimz)
> Persian language improvements made by:

- en/django_forms/README.md
> Fixed typo

- fr/css/README.md
- fix path to blog/static//css/blog.css
- fix errant line in the same file.
> Fix some typos in the french translation

- en/css/README.md
- Changed the color of h1 and h2 tags from #C25100 to #FF8833
The color of the header text, was a darker shade of orange and did not match the screenshot in the tutorial. The new color #FF8833, is a much more lighter shade and matches better.
> changed the color of the h1, h2 tags

- en/whats_next/README.md
-Added Coursera's Django for Everybody Specialization in the list of file README.md located at en/whatsnext  
-
-
> added coursera's django for everybody specialization

- it/SUMMARY.md
- it/deploy/README.md
- it/django_start_project/README.md
- it/python_installation/README.md
- it/python_installation/instructions.md
- 🇮🇹 Istallazione -> Installazione
> Fix typo in Italian language: installation is 'installazione' 🇮🇹

- book.json
- en/deploy/README.md
- en/django_admin/README.md
- en/django_forms/README.md
- en/django_models/README.md
- en/django_start_project/README.md
- en/django_urls/README.md
- en/django_views/README.md
- en/dynamic_data_in_templates/README.md
- en/template_extending/README.md
- en/whats_next/README.md
> NOTE: This update is only for the English language.
This is a followup from #1678
> Migration to Django 3.1

- en/deploy/README.md
- en/django_forms/README.md
- en/django_templates/README.md
- en/extend_your_application/README.md
- en/html/README.md
> NOTE: This update is only for the English language.
This is a followup from #1680
> Updating git inside tutorial

- en/python_introduction/README.md
Closes #1667
(as it contains the change from there, too)
-  a8c454339a6f44299f35609d4c7d932e195f9116 add example of function result comparison (taken from #1667)
- 2ba987719215ff68325ece92e173aa5ed367d10d call `len()` a function rather than a method
- 692ce04a43ea6bbe1d3488e16ed8f9f3a7ed2fae add detail to the explanation of what can be compared
> Add example of function result comparison and add more details to explanation of possible comparisons

- en/chromebook_setup/README.md
- en/code_editor/README.md
- en/deploy/README.md
- en/django_installation/README.md
- en/python_installation/README.md
Link to installation chapter where we refer to it
(Follow-up to https://github.com/DjangoGirls/tutorial/pull/1686#pullrequestreview-530807696)
> link to installation chapter

- en/README.md
- en/deploy/README.md
- en/django_forms/README.md
- en/extend_your_application/README.md
- en/html/README.md
- en/python_introduction/README.md
End sentences with proper punctuation, i.e., `.`, `!` or `?`, even when an `:)` emoticon follows.
> end sentences with proper punctuation, even when ":)" follows

- en/deploy/README.md
fixes #1694
- hardcode PythonAnywhere Python version to 3.8
> hardcode PythonAnywhere Python version to 3.8

- ko/README.md
My english name is Jay Park and korean name is 박제권. You can confirm it on the linked page( https://jinto.pe.kr) after the name .
- Name of a translater.
> Put 박제권's (Jay Park's) name in Korean.

- en/whats_next/README.md
- fa/django_urls/README.md
- from django.contrib import path, include 
include isn't in django contrib
> fix import include

- en/django_start_project/README.md
add blank line in source before itemized list as otherwise Crowdin [will mistake](https://crowdin.com/translate/django-girls-tutorial/306/en-de#14666) the first list item to be part of the paragraph preceding the list.
> add blank line in source before itemized list

- it/README.md
- it/SUMMARY.md
- it/chromebook_setup/README.md
- it/chromebook_setup/instructions.md
- it/code_editor/README.md
- it/css/README.md
- it/deploy/README.md
- it/deploy/install_git.md
- it/django_forms/README.md
- it/django_installation/README.md
- it/django_installation/instructions.md
- it/django_start_project/README.md
- it/django_templates/README.md
- it/dynamic_data_in_templates/README.md
- it/extend_your_application/README.md
- it/html/README.md
- it/intro_to_command_line/README.md
- it/python_installation/README.md
- it/python_installation/instructions.md
- it/python_introduction/README.md
- it/template_extending/README.md
- it/whats_next/README.md
* Andrea Stagi (https://crowdin.com/profile/astagi)
* GiorgioHerbie (https://crowdin.com/profile/giorgioherbie)
* Ivan Fossati (https://crowdin.com/profile/vania1366)
* Sara Castiglioni (https://crowdin.com/profile/sara.casti)
* sferrara (https://crowdin.com/profile/sferrara)
> Italian translation improvements from Crowdin made by:

- en/django_installation/instructions.md
A few minor fixes (w.r.t. grammar and clarity) to the Django installation instructions
> Minor fixes to Django installation instructions

- sk/python_introduction/README.md
Variable `hlasitost` was translated but a few occurrences of the original `volume` were left behind.
Fixes https://github.com/DjangoGirls/tutorial/issues/1771
> Fix: Forgotten variable translation

- bg/django_start_project/README.md
- cs/django_start_project/README.md
- de/django_start_project/README.md
- el/django_start_project/README.md
- fa/django_start_project/README.md
- fr/django_start_project/README.md
- hu/django_start_project/README.md
- hy/django_start_project/README.md
- it/django_start_project/README.md
- ja/django_start_project/README.md
- ko/django_start_project/README.md
- pl/django_start_project/README.md
- pt/django_start_project/README.md
- ru/django_start_project/README.md
- tr/django_start_project/README.md
- uk/django_start_project/README.md
- zh/django_start_project/README.md
- Changed to use `pathlib.Path` instead of `os.path`
> Update STATIC_ROOT to the latest Django style

- bg/django_start_project/README.md
- cs/django_start_project/README.md
- de/django_start_project/README.md
- el/django_start_project/README.md
- es/django_start_project/README.md
- fa/django_start_project/README.md
- fr/django_start_project/README.md
- hu/django_start_project/README.md
- hy/django_start_project/README.md
- it/django_start_project/README.md
- ja/django_start_project/README.md
- ko/django_start_project/README.md
- pl/django_start_project/README.md
- pt/django_start_project/README.md
- ru/django_start_project/README.md
- tr/django_start_project/README.md
- uk/django_start_project/README.md
- zh/django_start_project/README.md
- Changed to use `pathlib.Path` instead of `os.path`
> Update DATABASES to the latest Django style

- README.md
> Update README.md fix url to `https`

- book.json
- Add DigitalOcean ad to sponsor ads in the sidebar
> Add DigitalOcean to sponsors

- pt/intro_to_command_line/README.md
> Fix typo "mand" to "man"

- en/intro_to_command_line/README.md
I imagine it's confusing for folks that are new to the command line as to why their mouse isn't working when they try to move the cursor.
- Add a note about how to edit commands
Great tutorial, thanks!
> add note about editing commands
