DjangoGirls/tutorial

pl/css/README.md, pl/deploy/README.md, pl/django_forms/README.md, pl/django_start_project/README.md, pl/django_templates/README.md, pl/how_internet_works/README.md, pl/html/README.md, pl/intro_to_command_line/README.md, pl/whats_next/README.md
Some typos found&corrected, some sentences edited to sound more natural in polish
p.s. this is my first pull request, so if anything is broken - please be gentle with me!
=> DG tutorial POL - proof-read

en/django_start_project/README.md, pl/django_start_project/README.md, uk/django_start_project/README.md
This means we don't have to have two lines for windows and posix systems.
Thanks to @lenarother and Nika for pl/uk translation!
=> startproject commands are the same for win/posix

en/django_start_project/README.md
Move the note about virtualenv back, so the command is right after the instruction to run it.
Also, include the prompt in the command, since the instructions explicitly say to not type it.
=> Better instructions to run `django-admin startproject`

en/django/README.md, en/django_start_project/README.md
No more than the title suggests.
=> Change "Postman" to gender-neutral "Mail Carrier".

en/django_installation/README.md, pl/django_installation/README.md, uk/django_installation/README.md
=> Bump django version to 1.7.7

en/python_introduction/README.md
Get rid of improper usage of word "set" in favour of word "sequence". From Python point of view a set keeps unique values. A string is not set of characters, it's a sequence. The same about "instructions" in a function.
=> Wrong usage of word "set"

en/django_start_project/README.md
* Reorder timezone settings to the order they are displayed in settings.py
* Explain why the `.` is needed when using the startproject command
=> Minor updates to "Starting a django project"

en/deploy/README.md
My team got quite confused when they had to reopen the command line after doing the Heroku thingies and the next commands weren't working. It would be nice to have a reminder here because activating the virtualenv was ages ago :)
=> Activate virtualenv after command prompt restart

en/django_start_project/README.md, en/django_templates/README.md
Attendees usually find it confusing to get back to Django Installation chapter each time they need to activate the virtualenv, so I thought it may be handy to have it here too (as usually this is the chapter they go to directly after Intro to Python).
=> activate virtualenv in Start Dj Project

en/python_introduction/README.md
I feel that the line ``NameError: name 'names' is not defined`` could be a bit confusing. Too many ``name``s! I think it's clearer if the variable we're using has nothing to do with the string "name". I've also made the incorrect variable name a typo of the correct one, which ties in with the explanatory text that follows.
On the other hand, the example now differs from those before and after it, so I totally understand if you'd rather not make this change.
=> Change some potentially confusing naming

en/deploy/README.md
Hope it'll fix #297 
I'm not a native English speaker so please check my grammar ;)
=> working directory warning and git status intro

en/django_installation/README.md
Yesterday, I was helping my team to set up their laptop for the first DjangoGirls Paris and we encountered an issue during one of the installations. It appears that virtual environments do not work well with paths containing non-ascii characters (in particular, French accents).
So, I updated the tutorial to advise readers to be careful when creating their virtual environment in a directory whose path may contains accents and special characters.
=> Advise readers not to use non-ascii characters

en/django_forms/README.md
My students had a few difficulties comprehending some of the form logic. These difficulties came from the fact that they didn't understand how the `POST` attribute on the `request` object was related to a blog `Post`. This was made clear once I explained the different types of HTTP request (GET, POST etc.) and that the conflating terms were just a coincidence.
=> Conflating terms: POST (http method) vs Post (Django model)

en/python_introduction/README.md
Changed `compilier` to `compiler`.
=> Fixed minor typo.

en/deploy/README.md
without this, the `<your-username>` gets swalled because markdown things it's an html tag.
=> fix a markdown rendering issue in deploy chapter

en/deploy/README.md
Github link contained an additional ' which broke the link when clicking on it.
=> fixing broken github link

en/django_start_project/README.md
On Windows, hostname may include non-ascii characters encoded by locale-specific encoding.
`runserver` tries to do `gethostbyaddr`, which then fails with `UnicodeDecodeError` as it always try to decode with `utf-8`
Providing IP explicitly (even if it's `0.0.0.0`) enforces Django to skip this resolv, serving as a workaround for [Python's bug #9377](http://bugs.python.org/issue9377).
=> Provide alternative runserver command for Windows

en/django_forms/README.md
so that it matches Chapter "Extend Your Application"
More progress from #241
=> Making post_detail.html more consistent

en/python_installation/README.md, es/python_installation/README.md, fr/python_installation/README.md, pl/python_installation/README.md, uk/python_installation/README.md
...and added some consistency in terms of spacing.  I also included Debian in the Ubuntu header.
=> Added support for Fedora 22

en/django_orm/README.md, en/django_urls/README.md, en/html/README.md
While coaching at the Ensenada workshop I received questions from multiple students about whether commands needed to be run on PythonAnywhere.
This pull request provides some suggestions for answering some of these questions before they arise.  I am not particularly satisfied with the wording, but I haven't thought of anything better yet.
A couple alternative solutions:
- Add a section explaining that all commands after the deployment section are to be run in your local console unless it specifically says to run them on PythonAnywhere
- Change the appearance of code sections that should be run on PythonAnywhere (maybe change the color or font) and explain the difference
Feel free to close this pull request in favor of a better solution.
I have never coached students with the Heroku …
=> Clarify whether commands should be run on PythonAnywhere

en/django_start_project/README.md
To draw attention to the missing period, I've made it the only thing which we really hammer home to the student in that section. I agree with the comments by @helenst that reminding the student not to type ```(myenv)``` etc is less important. If they do type that it will be an immediate failure (without repercussions) and so I have moved the explanation about this concept to *below* the command instructions.
=> Fixed 377 - Drew more attention to the period in the command

es/css/README.md, es/django_forms/README.md, es/django_models/README.md, es/django_orm/README.md, es/django_templates/README.md, es/django_urls/README.md, es/django_views/README.md, es/extend_your_application/README.md, es/html/README.md, es/intro_to_command_line/README.md, es/python_introduction/README.md
Related to this issue: https://github.com/DjangoGirls/tutorial/issues/389
=> Fixed #389 -- Clean format in spanish version

en/python_introduction/README.md
I read the tutorial a couple days ago and noticed it has an example  to delete an item in a dictionary but non for the lists and that can leave a newbie wondering what is its equivalent so I added an example of list item removal.
I removed the programmers are lazy mostly because it was not mentioned previously as stated in that sentence and because I believe that, it is a stereotype that can give the wrong impression to some people. 
I added an additional explanation on why range does what it does because I felt that was incomplete since the notice told us to notice that but didn't clearly tell us that, that's how that function works. So I tried to kind of fix that.
Also I believe "programmers" sounded better than "computer people" so I changed that too.
I was thinking that it will be …
=> Added list delete example and minor changes

en/django_start_project/README.md
Writing django-admin.py simply opens the file with the default text editor.
=> django-admin not django-admin.py for windows

en/code_editor/instructions.md, en/django/README.md, en/django_models/README.md, en/django_start_project/README.md, en/intro_to_command_line/README.md, en/python_introduction/README.md
Cleanup some wording and example output based on running through first part of tutorial with Python 3.4.3 and Django 1.8.
=> Cleanup some wording and example output

en/django_templates/README.md
I was coaching the tutorial today, and everyone I watched go through this step replaced all 4 tags with `{{ posts }}` instead of replacing the full content, and were confused when their output did not match the screenshot.
This was the clearest I could word it, but open to changes to make it more clear.
=> clarify what to replace in the template section

en/intro_to_command_line/README.md
While coaching this, I had 2 of my 3 students almost wipe their installation directory that we setup in the Installation step.  The difference between ~/djangogirls and ~/Desktop/djangogirls wasn't clear enough.  This rename should remove that confusion.
Thanks for all the awesome work!
=> Avoid confusion by using different directory name

en/django_forms/README.md
The link is awesome but, if followers stop at the end of the official tutorial, they have a large hole in their site that allows third-parties to post to their app for them. This is a minimal step to make it more secure for those that don't get to the end of the second tutorial extension.
=> Add a bit of security to the "add new post" link

en/deploy/README.md
Add virtualenv name to prompt for the collectstatic example.
=> add virtualenv name to prompt

en/extend_your_application/README.md
Hi! I was reviewing the tutorial for mentoring DjangoGirls at DjangoCon :tada:.
I stumbled a bit over the Extend Your Application chapter  because I kept losing my place in the page scroll. There's a lot of code snippets that look very similar and very few section headings as a visual cue for where you in the page.
I suggest adding a few subsection titles and a few other edits to be a bit more specific with terms like "it". Please use what you think might be helpful. I like this section quite a bit and making it more user friendly would help :sunflower: :rabbit: :tulip:
=> Suggest user friendly edits for Extend chapter

pl/deploy/README.md
python-3.4.2 is not available on heroku
https://devcenter.heroku.com/articles/python-support#supported-runtimes
=> Update README.md - heroku python

en/deploy/README.md
Some users in chat expressed confusion why their posts were gone after deploying to PythonAnywhere.  One note was added in the "deploy" section to separate out test versus production systems.  Another paragraph briefly outlined the develop-test-commit-deploy cycle used throughout the rest of the tutorial.
=> Clarify confusion addressed in chat re:production data

en/deploy/README.md
This pull request includes two changes:
- Add `/static` to `.gitignore` (see #471)
- Remove "top-level" wording when discussing where to save the `.gitignore` file
One of my students asked me what "top-level" meant and I realized this wording may have been from a time when "mysite" was "djangogirls" so there was a `djangogirls/djangogirls` folder and the top-level one was the root folder.
I'm happy to use rebase to remove one of these commits if desired.
=> Add /static to .gitignore and clarify file location

en/deploy/install_git.md, en/django_installation/instructions.md, en/python_installation/instructions.md
Style the linux command prompt as `$` as opposed to including the current
directory name in the prompt.
Correct name of the python 3 package on Fedora 22 is `python3`.
Differentiate between Ubuntu/Debian/Fedora in Git installation
instructions.
=> Command prompt styling and other small improvements

en/extend_your_application/README.md
Minor change. Refer to error page as "TemplateDoesNotExist" instead of "Page not found", since that is the text shown to the user.
=> Change error name to reflect that shown to user

en/django_forms/README.md
because this error could happen right after trying to save the form. Right now users will not go on reading the next section about form validation when this error is popping up and therefore will not see its solution.
=> Pulled up note about logged out user error message

pt/deploy/README.md, pt/django_admin/README.md, pt/django_forms/README.md, pt/django_installation/README.md, pt/django_urls/README.md, pt/django_views/README.md, pt/dynamic_data_in_templates/README.md
The portuguese tutorial use different versions of Django across files.
This patch updated all the references to current stable version 1.8.5.
=> Updated portuguese tutorial to point to Django 1.8.

pt/django_start_project/README.md
`(myvenv) C:\Users\Name\djangogirls> django-admin.py startproject mysite .`
- [en] Kept opening up a dialog box "Open with" to select a web browser.
I've read in stackoverflow that it must be a virtual environment bug.
- [pt-br] Abria um pop-up "Abrir com" para selecionar um browser.
Li no stackoverflow que era um bug do ambiente virtual.
`(myvenv) C:\Users\Name\djangogirls> python myvenv\Scripts\django-admin.py startproject mysite .`
- [en] worked fine.
- [pt-br] funcionou perfeitamente.
=> Fixing command line

pt/html/README.md
`(myvenv) C:\Users\Name\djangogirls> django-admin.py startproject mysite .`
- Kept opening up a dialog box "Open with" to select a web browser.
- Abria um pop-up "Abrir com" para selecionar um browser.
`(myvenv) C:\Users\Name\djangogirls> python myvenv\Scripts\django-admin.py startproject mysite .`
- worked fine.
- funcionou perfeitamente.
=> Mismatching Instruction.

README.md
The existing documentation referenced a `contributing` branch in the git output, but creating this branch was never detailed in the instructions. I've confirmed that GitBook doesn't appear to do this for you, so I've added it under the `git clone` command. 
I tried to keep the new copy in line with the current tone, but I'm more than happy to accept changes to make it match better.
=> Add note to create a branch before starting to edit in contributing README.md

en/installation/README.md
noticed it for the current Budapest event - K.
=> python_introduction link was intro_to_command_line

hu/code_editor/README.md, hu/deploy/README.md, hu/django_installation/README.md, hu/installation/README.md, hu/python_installation/README.md
All include paths should be absolute. English version of tutorial has it right, but for some reason, in crowdin there're relative paths...
=> Fixed include paths.

en/whats_next/README.md
There are instructions in the repo for going through the tutorial, so it should be a good replacement for the website :).
=> Broken link: updated Django carrots to the repo

hu/django_forms/README.md
fix by removing tags raw and endraw from fenced html block
=> fix `TemplateSyntaxError at /post/2/edit/` `Invalid block tag: 'raw', expected 'endblock'`

it/deploy/README.md
The text "Scegli la versione "HTTPS", copialo, e incollalo nel terminale a breve" does not make much sense in italian.
It can be removed since on the next lines the concept is explained well enough.
=> Removed line that generates misunderstanding

es/intro_to_command_line/README.md
'ls/dir' was a confusing for some of the girls on the workshops where I have participated. I think that separating ls and dir and indicating the operating system is a little clearer.
Thanks! :-)
=> Fixed instruction that was confusing

en/python_installation/instructions.md
On Fedora 20 and Fedora 21, doing 'yum install python3.4' as currently documented, 
returns 'No package python3.4 available.'.
Doing 'yum install python3' installs python3.4.x
=> Update python install instructions for Fedora

book.json
To prevent contributors to make micro PR to fix typo, we could replace the "edit this page on github" link by a social button linking to this github repository (example [here](https://djangogirls.gitbooks.io/django-girls-tutorial-extensions/content/)).
The button is a bit small but don't forget that the introduction have a paragraph about on how to contribute with a link to the repository and contributors guidelines :wink:
=> Change link to Github plugin

ru/python_installation/instructions.md
For some reason everything here is about 3.4.3, but link was pointed to 3.4.2
I didn't change 59th line, but somehow it marked as changed as well :whale:
=> Change python version in a link for OS X

en/deploy/README.md, en/django_models/README.md
In the Models chapter, I noticed participants of the PDX event this previous weekend seeing their posts with the title "Post object." It turned out to be an indentation error. I wanted to make it more clear that the methods needed to be indented inside the class to help future participants.
In the Deploy chapter, it seemed a little confusing to not explain that we would be moving back to our local environment to make changes. One participant made manual changes to her GitHub repo, which was confusing for her when she couldn't push without pulling changes down locally first. I thought this note might help.
=> Changes to Models and Deploy Chapter

en/css/README.md, en/deploy/README.md, en/django_forms/README.md, en/extend_your_application/README.md, en/html/README.md
Enabling the same WSGI middleware that is used by runserver allows us to simplify the static files process, and remove a bunch of steps.
As discussed in #641
=> Remove need for whitenoise and collectstatic

es/README.md
Link was broken. I guess pointing to the English contribution instructions is the way to go.
=> Changed link to contribution instructions.

en/django_urls/README.md
Django 1.9 validation may kick in here, and cause the `AttributeError module has no attribute post_list` to appear in the command line console rather than on the site with the debug view.
=> clarify AttributeError location

es/django_start_project/README.md
Fixed line 15 command to activate the virtualenv on Mac OS. Keyword 'source' was missing.
=> Update Spanish README.md

en/django_urls/README.md, en/django_views/README.md
Looks like initialisation now tries to import view functions at server start, so you don't get to the DEBUG = True style error page any more. I've changed this, but kept the comments about friendly error pages elsewhere.
=> Make missing view function error more accurate for 1.9

fr/django_orm/README.md
Invalid syntax on line 123 in chapter django_orm (FR version)
Should be done on two lines to avoid "SyntaxError: invalid syntax"
=> Invalid syntax on line 123 (django_orm chapter - FR version)

en/django_installation/instructions.md
as renaming or moving a virtualenv directory will break it.
Reword warning to delete & create new virtualenv in new directory.
(Suggested order is to create new & then delete the old one, just in
case one needs to refer to the old one for any reason.)
(see "Normally environments are tied to a specific path. That means
that you cannot move an environment around or copy it to another computer."
in https://virtualenv.pypa.io/en/latest/userguide.html#making-environments-relocatable)
=> Remove advice to move virtualenv directory

en/deploy/README.md, en/django_installation/instructions.md
Install latest release of Django 1.9 (1.9.4 as of the time of this writing) instead of the first 1.9 release. The original suggested install method may lack critical security fixes added in later patches.
This syntax should work even if there weren't any point releases yet.
Tested on Linux under Bash, please test on Mac and Windows, if the quoting style is portable.
=> Install latest release of Django 1.9

en/django_installation/instructions.md
People don't always understand they need to type things if the `$` sign is missing. This should make it slightly clearer and consistent with the rest.
=> Add $ before commands in Virtual Environment installation

en/django_models/README.md
Fix for #712 - Update directory tree for blog to show "apps.py" on Step 10: Django models.
I have also added `db.sqlite3` in the tree structure and ignored the `myvenv` directory
=> "apps.py" included in directory tree on Step 10. Django models

en/html/README.md
5c1d220a7e00a4ecf10539124bd56130fecd0983 changed -A to --all but the
note wasn't updated. This only fixes it for English, but should be done
for all languages.
See https://github.com/DjangoGirls/tutorial/pull/749 as well.
=> Remove outdated mention of -A

en/html/README.md
When you navigate into the project directory at that point of the tutorial in pythonanywhere you actually see something along the lines of:
```
(myvenv) somestuffhere (master)$
```
I think it's simpler to not have the `(myvenv)` part at all (since it's not needed/relevant in that step) and only have what people need to type in.
Otherwise it can get confusing as the previous command doesn't have the same prefix.
=> Remove confusing (myvenv) from pythonanywhere prompt

en/deploy/install_git.md
Changed text to match the actual wording used in the Windows Git installer.
=> Update install_git.md to match Windows installer

en/deploy/README.md
When filling the venv path in PythonAnywhere, it says `/home/<your-username>/my-first-blog/myvenv/`.
This <your-username> is easy to confuse with previous places where `<your-username>` referred to the github or computer username, so I suggest to make it more explicit
=> PythonAnywhere app instructions fix

en/python_installation/instructions.md
During installation night, one of our Windows users (Windows 10) ran
into the case where the tutorial was telling her to run some command
line tools before telling her how to open Command Prompt. The OSX
instructions tell the user to open Terminal (although don't explain
how), so I added a section on how to launch Command Prompt and hint that
it will be explained in a forthcoming section.
=> In Installation, tell Windows folk how to open cmd

en/python_introduction/README.md
Currently coaching and I realized Many people following the tutorial, and using windows OS are running into the same mistake. I was thinking putting a reminder of 'python' instead of 'python3' could make things easier
=> Added Python Execution in Windows

en/django_installation/README.md
Windows 10 computer might receive message “execution of scripts is
disabled on this system.” message to prevent users to continue or work
in venv. To correct this error, the user needs to set execution policy
to apply to All.
=> Added possible error message for Windows 10 users

en/css/README.md
Adding a hint as to the order of the addition of the lobster font to the CSS.
If the new line is inserted after the link to `blog/static/css/blog.css` then the font doesn't change. We (with @maxwell-k) noticed this at the second Belfast DjangoGirls event.
=> Line order instruction about Lobster font

en/chromebook_setup/instructions.md
Minor correction: Need at the prompt 'python3.5' instead of 'python3' when creating 'myvenv' virtual environment in the tutorial
=> Correction python3 to python3.5 at prompt in Tutorial

en/chromebook_setup/instructions.md
This is probably the wrong way to do this, but when reading the installation instructions I wasn't sure how far to skip down the page to skip the Chromebook instructions. So I added a link that would skip down the page for you.
=> Provide link to skip Chromebook instructions

en/python_installation/instructions.md
While following the installation instructions, we got a message that said the Python installation pkg "is damaged and can't be opened." Googling the error indicated we needed to change the setting to allow apps downloaded from identified developers, so I added that as a callout in the docs.
=> Include security change on OS X before installing a pkg

en/django_start_project/README.md
This matches both with the image below and standardizes, since the tutorial uses "127.0.0.1" later on in http://tutorial.djangogirls.org/en/django_admin/#django-admin.
=> Change localhost to 127.0.0.1

fr/deploy/README.md, pt/deploy/README.md
In the french and portuguese translations, a particular file path in the "Deploy!" step is higlighted with bold (*) instead of backticks (`). This is causing issues with the username placeholder because of the way the Markdown is interpreted:
*/home/<your-PythonAnywhere-username>/my-first-blog/myvenv/* vs `/home/<your-PythonAnywhere-username>/my-first-blog/myvenv/`.
Edit: I spotted this issue in the french translation first, then did a global search and haven't found it anywhere else but the Portuguese translation.
=> Fix path highlight hiding username placeholder

fr/deploy/README.md, pt/deploy/README.md
The original english text says:
> In the "Virtualenv" section, click the red text that says "**Enter** the path to a virtualenv", and **enter** `/home/<your-PythonAnywhere-username>/my-first-blog/myvenv/`.
The french translation says:
> Dans la section "Virtualenv", cliquez sur le texte en rouge qui indique "**Enter** the path to a virtualenv" (**ajouter** le chemin d'accès de votre environnement virtuel), et **ajouter** ceci : `/home/<your-username>/my-first-blog/myvenv/`.
Enter shouldn't be translated as "ajouter", whose most common translation would be "add". Here we really don't want people to add that path at the end of whatever is in that field. "Entrer" is the appropriate word here – a common translation for "Enter" in the IT context, eg. "Enter your password" – "Entrer votre mot …
=> Change verb in french translation

ko/django_forms/README.md
Modified to correctly run when deployed on pythonanywhere.com
it redirected to wrong url: (yourID.pythonanywhere.com/post/new/blog.views.post_detail).
However, after this modification it redirects to correct url: (yourID.pythonanywhere.com/post/post_no)
=> redirect target fixes

en/deploy/README.md
Gedit creates ~ files in Ubuntu and should be ignored by git.
=> *.~  added in gitignore

book.json, en/deploy/install_git.md, en/django_installation/instructions.md, en/installation/README.md, en/python_installation/instructions.md
Use the `sectionx` extension to put instructions for different operating systems in separate sections to address #862 .
Started with the Python installation instructions to show what it might look like.
Add `sectionx` to:
=> Add sectionx and use in installation instructions

fr/html/README.md
We had `--all` in the code and `-A` in the Note.
Use `--all` everywhere decreases risks of confusion for the reader.
On avait `--all` dans le code et `-A` dans la note.
Utiliser `--all` partout évite une confusion pour le lecteur.
=> Use the same --all argument everywhere

en/python_installation/instructions.md
One of my team members could not install Python 3.5.1 nor 3.5.0 in a Windows 7 machine.
The error we came across seems related to these:
http://bugs.python.org/issue25157
http://bugs.python.org/issue25265
https://bugs.python.org/issue25546
We tried to install http://www.microsoft.com/en-us/download/details.aspx?id=48145, as suggested in the last link, but that installer gave us the same error as the Python installer...
What worked for us was to install Python 3.4.4 using the "*.msi" installer.
=> Add note about installing Python 3.5 in older Windows versions

en/deploy/README.md, en/deploy/install_git.md
This means the explain of what git actually is will be included
in the install instructions page as well.
=> Move explanation of Git to the 'install' file

en/django_installation/instructions.md
Putting it inline makes it less clear where to type it, and also makes people include the '.' when they shouldn't.
=> Make pip upgrade instruction clearer

en/python_introduction/README.md
`\*` will throw an error if used as an operator - it should just be `*` as in `2 * 3`. It looks correct in the other tutorial translations.
=> Fix `\*` typo

en/python_introduction/README.md
Hello, this is an attempt to help with https://github.com/DjangoGirls/tutorial/issues/196
Specifically, @vrutkovs's suggestion:
> People usually read the chapter line by line and get confused that
> things break (on such an early stage). The coach has to know this
> situation in beforehand and warn the student (I almost filed a bug about
> incorrect syntax in the example)
This PR just mentions some things that can go wrong when defining a function, instead of saying "that was easy".
I think adding some styling to display these kinds of things in a different way would help a lot, but I wanted to try and see if rephrasing some bits would help. Happy to extend this if it's helpful, but wanted to keep it simple to start with as I haven't read the full tutorial myself.
=> Mention some possible errors in the python intro

en/django_start_project/README.md
On several occasions, we had confusion about the contents of the directory after running the django-admin.py script. The directory tree suggests to show all the contents, but in fact, when following the installation guideline, venv will also sit in the djangogirls directory. This is missing in the pic, so participants sometimes think it is an error and might try to delete it. I suggest a note to fix this.
=> Added clarification about directory content

en/django_orm/README.md
There's an interactive Python without the `>>>`. Fixed it.
=> Consistency: Missed a `>>>`

ru/django_forms/README.md
With "blog.views.post_new" our educate blog will throw "NoReverseMatch at /
Reverse for 'blog.views.post_new' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []".
=> Replacing "blog.views.post_new" by "post_new"

cs/django_orm/README.md, en/django_orm/README.md, es/django_orm/README.md, fr/django_orm/README.md, hu/django_orm/README.md, it/django_orm/README.md, ko/django_orm/README.md, pl/django_orm/README.md, pt/django_orm/README.md, ru/django_orm/README.md, sk/django_orm/README.md, tr/django_orm/README.md, uk/django_orm/README.md, zh/django_orm/README.md
In Django 1.10, QuerySet repr() was changed to distinguish it from an ordinary
list (https://docs.djangoproject.com/en/1.10/releases/1.10/#miscellaneous).
Update the command output in the tutorial to reflect this.
=> Update QuerySet representations to match Django 1.10

en/django_start_project/README.md
Start server on port 8000, as that is the port we'll access with the browser [further below in these instructions](https://github.com/das-g/django-girls-tutorial/blame/ea7948eb5a6c62197635cb39f570a149a02c4035/en/django_start_project/README.md#L173).
=> start server on port 8000

en/chromebook_setup/instructions.md
On the latest Cloud 9 VM, an update is required before python3.5-venv will install.
This is a replacement/improvement for the earlier pull request: https://github.com/DjangoGirls/tutorial/pull/1051
=> Add sudo apt update command

pt/deploy/README.md, pt/django_forms/README.md, pt/django_installation/README.md
On the PythonAnywhere step on "pt" version, there's a `pip install` install step that doesn't mention the same version recommended on the django install step. 
So at the django install step I've added a `pip freeze` and on deploying I've fixed this issue with a `pip install -r requirements.txt`.
Also, I have fixed a small typo on the forms step.
=> Fixed Django version on PythonAnywhere and reviewed some typos

pl/deploy/README.md, pl/django_models/README.md, pl/django_start_project/README.md
Fixes for typos in Polish translation to have `myvenv` consistenly in the whole tutorial.
cc @asendecka
=> [Polish] Fixed typos

en/python_installation/instructions.md
The linked support page does not cover Windows 10, and has complex
different steps for each other version of Windows.  The Win+Break
shortcut should work on many versions of Windows and is simple.
=> Simpler, clearer way to check for 32/64-bit windows

en/django_start_project/README.md
Corrected the port the server is run on when using Cloud 9 - should be 8080, not the standard 8000.
=> Corrected Cloud 9 port

crowdin.yaml
I have asked a question on slack regarding sync of tutorial between Github and Crowdin (https://djangogirls.slack.com/archives/C03PLJLM8/p1494944212777047).
This pull request resolves issue with syncing source language (`en`) from Github to Crowdin and define, where Crowding should commit translated assets. It also removes few unnecessary options.
Somebody (maybe @olasitarska  as an owner on Crowdin) should also check if API key to project on Crowdin has been regenerate as it cause potential vulnarebality (`This key gives full access to all your Crowdin project data. Treat this just like a password!` see: https://crowdin.com/project/django-girls-tutorial/settings#api)
=> Proper definition of Crowdin assets

en/deploy/README.md
By using os.path.expanduser we automatically find the correct directory. This means the user doesn't have to modify anything making it easier. There is also no added value in doing this manually.
=> [English] Allow copy paste WSGI

cs/django_start_project/README.md
We found that there is misspelled `python` in one command.
=> [Czech] Fix typo in command

pl/deploy/README.md, pl/django_templates/README.md, pl/django_views/README.md, pl/dynamic_data_in_templates/README.md, pl/extend_your_application/README.md, pl/python_introduction/README.md
While preparing to workshops in Wrocław, Poland, I went trough whole tutorial on Windows 10, and found some places which could be phrased better to minimize friction.
The most important one is probably the issue with `ALLOWED_HOSTS` in settings.py, which perhaps should be reflected also in other language versions.
Other than that:
- I've fixed the keyboard shortcut for exiting from Python 3.4 on Windows 8+ according to 
https://stackoverflow.com/a/41524896/575699 and my experience.
- added some rough explanation of why we use `virtualenv` on PythonAnywhere but `venv` on localhost, based on https://www.reddit.com/r/learnpython/comments/4hsudz/pyvenv_vs_virtualenv/
- replaced some of uses of word "method" with "function" to match the distinction between the two introduced in the …
=> Pl win fixes

en/SUMMARY.md, ko/SUMMARY.md
As noted in Issues #1071 and #1072 , the markdown links to the Chromebook Setup page fail to load that page.
While the embedded instance works fine (visible within the tutorial's [Installation](https://tutorial.djangogirls.org/en/installation/#chromebook-setup-if-youre-using-one)), it may be that in order for the standalone page to be accessible, it needs to be accounted for in the table of contents. That's my understanding from https://github.com/GitbookIO/feedback/issues/467. 
This PR adds the chromebook setup to the table of contents for the EN and KO versions (the only ones with chromebook content).
=> Fix: links to Chromebook Setup

pt/python_introduction/README.md
'Ana' is a more common name than 'Ola' in Brazil, and it avoids confusion with the portuguese word for Hello, which is 'Olá'.
=> [Portuguese] Replace 'Ola' with 'Ana' in the examples of name

tr/django_forms/README.md
PostForm() is a class and we don't need to say anything about PostForm() type.
=> [Turkish] PostForm() type correction

pl/deploy/README.md
Using apostrophe as commit message enclosing symbol doesn't work on Windows. Replaced with ".
=> [Polish] Fix apostrophe in commit message

cs/python_installation/instructions.md, en/deploy/install_git.md, en/python_installation/instructions.md, es/python_installation/README.md, fr/python_installation/instructions.md, hu/python_installation/instructions.md, it/python_installation/instructions.md, ko/deploy/install_git.md, ko/python_installation/instructions.md, pl/python_installation/instructions.md, pt/python_installation/README.md, ru/python_installation/instructions.md, sk/python_installation/instructions.md, tr/python_installation/instructions.md, uk/deploy/install_git.md, uk/python_installation/instructions.md, zh/python_installation/instructions.md
According to https://fedoraproject.org/wiki/End_of_life Fedora 21 has been EOL since 2015-12-01. We can expect that users have upgraded by now or know to use yum instead of dnf.
Some languages still have instructions for older python versions and they're not likely to work anymore but I decided to leave that in for now since I don't speak those languages.
=> Remove instructions for old Fedora versions

en/extend_your_application/README.md
`blog.views.post_detail` is not in the source code example so the explanation in the following paragraph was not consistent with it. From what I understand, it is the URL created by Django, so I added this to the text.
=> Consistency between text and code example

book.json
The `sectionx` plugin now has a `tag` setting that defines the tag to use for the dropdown headers. Changing it to `b` tags means they take up less space and look a bit neater.
Addresses #1058
=> changed sectionx setting to make dropdowns neater

fr/deploy/README.md
The French version of the deploy step was still mentionning the fact that static files should be collected, which is not the case anymore since django.contrib.staticfiles.handlers.StaticFilesHandler is used in wsgi.py.
=> [French] Remove references to collecting static files for deploy

fr/django_start_project/README.md
In the English tutorial, in "Your first Django project", the participant sets ALLOWED_HOSTS to prepare for PythonAnywhere deployement. That part was missing in French.
=> [French] Add missing part about ALLOWED_HOSTS

pt/deploy/README.md
- Change instructions to install python3.5 on pythonanywhere instead of python 3.6 to make it coherent with the install instructions.
=> Change Python version while creating venv on PythonAnywhere

cs/python_introduction/README.md, de/python_introduction/README.md, en/python_introduction/README.md, es/python_introduction/README.md, fr/python_introduction/README.md, hu/python_introduction/README.md, it/python_introduction/README.md, ko/python_introduction/README.md, pl/python_introduction/README.md, pt/python_introduction/README.md, ru/python_introduction/README.md, sk/python_introduction/README.md, tr/python_introduction/README.md, uk/python_introduction/README.md, zh/python_introduction/README.md
Old error message is by Python 3.5, new by Python 3.6.
The tutorial now instructs to install Python 3.6, so it should also show the corresponding error messages.
=> fixed error message of TypeError for unorderable types

en/django_views/README.md
It's not true that the "simplest" *view* can look like this, because the import will still be needed. I am aware that it is mentioned before but one of the girls in my group removed it, since that's apparently the simplest the *view* can look like :).
- Add required import to view example
=> Clarify simplest view example

de/deploy/README.md
virtual environment python version does not match the pythonanywhere python version - this results in an error at pythonanywhere.com when trying to set the virtual environment.
=> fixed pythonanywhere python version to virtualenv python version

en/django_models/README.md
Not providing `on_delete` will give deprecation warning in Django 1.11 - will be required in Django 2.0.
See https://docs.djangoproject.com/en/1.11/ref/models/fields/#foreignkey
- Added `on_delete` positional argument to ForeignKey
- May currently alleviate some confusion, and required in upcoming Django 2.0.
=> Added 'on_delete' to 'ForeignKey' in Django models:

en/django_start_project/README.md
998120bbbdbdc8907f3e1178aadf416b022de5b3 moved from .pythonanywhere.com to <your_username>.pythonanywhere.com to fix a DisallowedHost error. I can't reproduce that and this is much easier because it allows copy-pasting.
=> Simplify ALLOWED_HOSTS configuration

en/html/README.md
The xhtml style is no longer recommended for use in HTML5.
=> Use HTML5 style br-tags

en/django_admin/README.md, en/django_models/README.md
During PyCon UK Django Girls workshop everyone in my group was using Windows. There was confusion when some sections only had Mac/Linux shell commands. Attendees would then copy/paste or re-type the whole Linux command (including the $ and so on) as they looked different to their Windows shell. Hopefully this fixes some of it going forward.
=> Avoiding confusion when sections don't have Windows commands

crowdin.yaml
I'm reopening this pull request with adding `%locale%` to crowding configuration. It will not help us a lot, but at least resolve an issue with:
It will also push all Crowdin translations to Github (there's always open pull request, that is automatically open by Crowdin for that, but is useless, as there's almost no possibility that we will merge all languages at the same time) - right now languages that are crashing in two letter code space (we are talking here about `zh-CN`  vs `zh-TW` and `pt-PT` vs `pt-BR`) overwrite each other translations.
To refresh Crowdin and resolve problem there and with overwriting translated assets here @aniav needs to check Github Integration configuration on Crowdin and pause the sync, and resume it.
=> Add %locale% to destination for target languages on Crowdin

cs/deploy/README.md
The .gintignore was not working properly because of the additional spaces.
=> Deleted spaces in the example .gitignore file

cs/django_models/README.md, de/django_models/README.md, en/django_models/README.md, es/django_models/README.md, fr/django_models/README.md, hu/django_models/README.md, it/django_models/README.md, ko/django_models/README.md, pl/django_models/README.md, pt/django_models/README.md, sk/django_models/README.md, tr/django_models/README.md, uk/django_models/README.md, zh/django_models/README.md
Django 1.11 shows a deprecation warning and Django 2.0 will give an error if on_delete is not specified on a ForeignKey.
This includes https://github.com/DjangoGirls/tutorial/pull/1212 and makes all languages consistent.
=> Add on_delete to ForeignKey in Django Models

en/python_introduction/README.md
This change fix translation/Crowdin issue.
When we use \`\`\` inside sentence as an inline code Crowdin divide it to 3 separate sentences for translation (in example below we have 2 occurance of \`\`\` so sentence was divided into 5 pieces):
Such situation is dificult for translator, as there's not so much option to switch syntax inside this "sentences".
=> Inline code use oneline code blocks

pt/intro_to_command_line/README.md
Fixes:
- section heading that was without dividing line
- two sections of linux commands were outside the area
=> fixed command line sections

en/deploy/install_git.md
The step name is sufficient, and more future-proof to changes.
This addresses part of #1224
=> Omit the step number in windows git installation wizard

en/deploy/README.md
This changes should fix an issue that occurs in Crowdin. Because of this space multiline code block is wronlgy parsed and span from https://crowdin.com/translate/django-girls-tutorial/296/en-pl#8808 up to https://crowdin.com/translate/django-girls-tutorial/296/en-pl#8816
Whole selection on screenshot is composed by one XPath selector - `/pre[4]/code`, I spoke with Crowdin support and they suggest, that this change will fix it.
=> Crowdin support fix for spanning one XPath into multiple translatable instances

en/deploy/README.md
pending writing our own tutorial-extension re security (https://github.com/DjangoGirls/tutorial-extensions/issues/101), and ref #802, this at least warns the user about not-ideal security settings, and points them towards the official Django deployment checklist (which discusses SECRET_KEY, DEBUG, etc)
=> Minimal security warning in deploy chapter. cf #802

.gitignore
Ignore VIM's temporary files `*.swp` and JetBrains's `.idea`
=> gitignore - ignore *.swp and .idea

en/chromebook_setup/instructions.md
=> fix typo in Chromebook Setup instructions

en/django_templates/README.md
Previously we cloned to my-first-blog but the current script deploys to
$USER.pythonanywhere.com. This corrects the step so students aren't
confused.
Fixes #1267
=> Correct cd command on updating the deployment

en/html/README.md, pl/html/README.md
One of the command blocks incorrectly specified target console. It should be PythonAnywhere not local one.
=> Add missing PythonAnywhere command description

en/python_installation/instructions.md
Move note about searching for "Command Prompt" to between the instructions for getting it from the start menu and the Win-R "cmd"-instructions, as the searching probably refers to within the start menu (which is searchable in newer Windows versions and might offer some entries only through search).
=> Move note about searching for "Command Prompt" to start-menu-based instructions

README.md
- Change occurrences of `Gitbook` to `GitBook`, for consistency and to match the official name.
- There's a new GitBook v2 that is considerably different than the GitBook used to produce the tutorial. Update links to the correct version.
=> GitBook spelling and links to legacy website

de/css/README.md, de/django_forms/README.md, de/template_extending/README.md, en/css/README.md, en/django_forms/README.md, en/template_extending/README.md, fr/css/README.md, fr/django_forms/README.md, fr/template_extending/README.md, hu/css/README.md, hu/django_forms/README.md, hu/template_extending/README.md, ko/css/README.md, ko/django_forms/README.md, ko/template_extending/README.md, pl/css/README.md, pl/django_forms/README.md, pl/template_extending/README.md, ru/css/README.md, ru/django_forms/README.md, ru/template_extending/README.md, sk/css/README.md, sk/django_forms/README.md, sk/template_extending/README.md, tr/css/README.md, tr/django_forms/README.md, tr/template_extending/README.md, uk/css/README.md, uk/django_forms/README.md, uk/template_extending/README.md
- Replace `{% load staticfiles %}` with `{% load static %}`
The usage of `{% load static %}` has been available since [Django 1.10](https://docs.djangoproject.com/en/dev/releases/1.10/#django-contrib-staticfiles).
The usage of `{% load staticfiles %}` has become deprecated in [Django 2.1](https://docs.djangoproject.com/en/dev/releases/2.1/#id2).
=> Replace {% load staticfiles %} with {% load static %}

en/django_installation/instructions.md
I.e. Django 2.0.x, where x ≥ 6
- change `==` to `~=` in `requirements.txt`, thereby making the smallest specified version component a minimum instead of a hard-coded exact value. This is equivelent to `>=2.0.6,<2.1`, but easier to adapt (and shorter).
=> Allow for higher Bugfix/Patch version of Django

en/extend_your_application/README.md
- change import sentence in `blog/urls.py`
=> Fix for #1305, fix urls.py example missing an import

en/django_installation/instructions.md, en/installation/README.md
Fix for #1306 : On the Installation page, install the code editor before Django  -- it is already in that order in the main flow of the document, but not in the one-page installation guide. Then when installing Django, say to use the code editor to create the requirements.txt file.
=> Install code editor before Django

en/deploy/README.md
As noted on #1332, the instructions said Copy but not Paste for the clone URL. So, changed to say to note the clone URL, and then when it is used twice later in the page, say something about how it should match the URL that you saw.
Fixes #1332
=> Remove suggestion to copy the clone URL

de/deploy/README.md
I'm a participant from the djangogirls workshop in Zürich. During the coaching we recognized, that the wording in the german tutorial at "Veröffentlichen" in the django section isn't really clear for the participants. I changed the wording and deleted an empty line and three spaces.
=> Change wording of "Basisverzeichnis"

de/django_templates/README.md
The English version says "replace everything from the second `<div>` to the third `</div>`" which seems correct.
=> Fix div tag in German translation

ko/deploy/README.md
- The url was enclosed in square brackets rather than parentheses.
=> Fix crashed markdown link

es/deploy/README.md
at the time of this writing, current (default) version is whitenoise==4.1. white noise 4.0 introduced breaking changes with respect to 3.3 that prevent the rest of the tutorial from working (http://whitenoise.evans.io/en/stable/changelog.html#v4-0)
=> pin version 3.3 of whitenoise

en/django_start_project/README.md
I found out the typo.
Please check it out.
- before: you [can can] add this to change the default buttons
- correct: you [can] add this to change the default buttons
=> Typo: Your first Django project! [you can can]

en/python_installation/instructions.md
- before: you need to use yum instead.
- after: you need to use `yum` instead.
=> Typo: Modified yum to show as a command

en/chromebook_setup/instructions.md
c9.io is now AWS Cloud9, and the instruction need to be updated. Added other instruction for other cloud IDE(PaizaCloud).
=> Update chromebook setup instructions

en/code_editor/instructions.md
Removes the "new" description of Atom. 
The description of Atom was added to the tutorial in 2014 in [80612f9](https://github.com/djangogirls/tutorial/commit/80612f94572a3dcb3679d8ec373385fc45580d5e).
Atom had its 1.0 release in Jun 2015.  🎉
=> reword description of the Atom text editor

en/django_views/README.md
- make clear that a regular value (the one returned by `render(...)` will be returned by the view
- switch that part of the sentence to future tense, to be somewhat more grammatical
=> Make clear that view does not return a function

en/intro_to_command_line/README.md
=> Add info on command help

en/intro_to_command_line/README.md
On https://tutorial.djangogirls.org/en/intro_to_command_line/ we're getting
> TO AUTHOR: There exists some syntax error in this page, check the build log for details.
In logs:
```
[gitbook-plugin-sectionx](intro_to_command_line/README.md)n
Error: The id for the section is not unique. Please fix the syntax for the following section:
Error: The id for the section is not unique. Please fix the syntax for the following section:
```
Bug introduced in #1393.
CC: @das-g @jhodgdon-drp
Thanks for report on Gitter go to @greghanley3
=> Make html id unique

en/deploy/install_git.md
The installation of git for windows has changed, most importantly it has added a step to choose the default test editor for creating commits. The default is Vim, which is pretty unfriendly for newbies, so I suggest using Nano.
Fixes: https://github.com/DjangoGirls/tutorial/issues/1224
=> [1224] Modifies git on windows instructions

en/installation/README.md
Proposed fix for #1014 . Instead of moving the Installation page to the end, it adds more notes at the top, including a section for people who are at workshops.
Fixes #1014
=> Add more notes to top of installation page

en/whats_next/README.md
After coaching a number of sessions over the last couple of years it's pretty clear that people come to the Django Girls tutorial for all kinds of reasons – maybe they want to create a website for their small business, maybe they want to use Python to help crunch data for their PhD – the audience is _really_ broad. With that in mind I wanted to flesh out and restructure the "What's next?" section of the tutorial to better help people find resources that are relevant to their interests so that they can better build on their experience of the tutorial.
The only resource I've removed from the original page is the book _Two Scoops of Django_ – I am a huge admirer of this book but I believe it is far too advanced to give to someone coming straight out of the Django Girls tutorial, and it costs …
=> Add more resources to "What's next?"

en/deploy/install_git.md
When comparing version control systems like Git to the "track changes" feature of word processor programs, not only the proprietary Microsoft Word (part of the Microsoft Office office suite) should be named, as the "track changes" feature is implemented in more than that one text processor / office suite. Also naming a FLOSS one (that is also available on FLOSS systems like GNU/Linux) seems required for completeness, and for the (probably still few) participants that never have used Microsoft software.
=> also name LibreOffice when comparing Git to MSWord "track changes" feature

en/django_models/README.md, en/django_start_project/README.md
connects to https://github.com/DjangoGirls/tutorial/issues/880
changes in this PR:
- alters the code snippet to use`settings.AUTH_USER_MODEL`
- updates console output of the database migrations, to reflect additional `auth` migrations
=> change 'auth.User' to settings.AUTH_USER_MODEL

en/css/README.md, en/django_forms/README.md, en/django_templates/README.md, en/extend_your_application/README.md, en/template_extending/README.md
Partially fixes #1338 
Fixes the text in tutorial pages to use better contrast color in the CSS, and to only have one h1 header on a page (others are changed to h2).
Screenshots still need to be updated.
=> Accessibility fixes

en/django_models/README.md
These lines are not too long and could confuse new users. Especially since the author is longer yet is on a single line.
=> Join lines in the model definition

en/python_installation/instructions.md
We have 3 open issues about Python version and package confusion. This PR attempts to fix them all:
- Fixes #1222: says that the python3.6 package is unavailable for Ubuntu, so the instructions are changed to use package python3
- Fixes #1259: talks about the fact that Linux installs probably already have Python. The instructions in this PR are changed to tell you which versions are OK and which ones you need to upgrade.
- Fixes #1322: talks about the Windows instructions, which both say to get the latest Python and to get 3.6. The instructions are updated to say to get the latest.
=> Clear up Python version confusion

tr/deploy/README.md
- Replace `git clone` command with the correct `pa_autoconfigure_django.py`
=> Fix PythonAnywhere command in Turkish translation

en/extend_your_application/README.md
Just a little typo.
It's also in 
```
de/extend_your_application/README.md
es/extend_your_application/README.md
ja/extend_your_application/README.md
pl/extend_your_application/README.md
tr/extend_your_application/README.md
```
but I don't know if you handle somehow with Crowdin.
=> Fix typo: `post_detail` urlpath

en/django_installation/instructions.md
- Update command step to use `python` instead of `python3` since we are working within the virtual environment. 
Thank you! :)
=> Added small note to use `python` instead of `python3` for Windows.

en/chromebook_setup/instructions.md
I've changed this sentence "This bottom area is your _terminal_, where you will give the computer Cloud 9
has prepared for your instructions" 
into:
"This bottom area is your terminal. You can use the terminal to send instructions
to the remote Cloud 9 computer."
=> syntax fixed

en/chromebook_setup/instructions.md
- added inline code (monospace) around "~="
=> use inline code markup for part of CLI input

en/intro_to_command_line/README.md, en/python_introduction/README.md
- Mention the possibility of the "Desktop" subfolder of Linux user home folder to be localized when that folder _first_ occurs in a command (in the command line intro chapter)
- (For that, introduce separate expandable sections for Linux and OS X)
- Give an example of a translated name. (I've chosen the German "Schreibtisch".)
- Adapt the existing remark at a later occurrence (in the python intro chapter) accordingly
This should ...
- ... help people following the English original of the tutorial despite having localized folder names. (E.g. because no (complete) translation of the tutorial is available for that language.)
- ... remind translators that they should mention how these folders are named on Linux accounts in the respective language.
=> [en] mention possibly translated dir name for "Desktop" at first occurrence

en/django_orm/README.md
Not QuerySets can be chained, but their method calls can.
- Mention that some QuerySet methods themselves return a QuerySet
- Correct language: It's the method( call)s that can be chained/combined, not several QuerySets.
- Change h3-section title to reflect this new content.
This is an alternative change to the one proposed at #1311. Other than #1311, this change **doesn't** try to explain how to combine several QuerySets with the `union` method, which isn't needed for the tutorial anyway.
=> correct language w.r.t. QuerySet method chaining

en/deploy/README.md
based on issue #1314
- fix `ls blog/`output (typed at pythonanywhere)
- add `apps.py`
- delete `forms.py`, `static` folder, `templates` folder and `urls.py` because they are not yet created at deploy chapter
Fixes #1314
=> fix ls output (at deploy chapter)

de/html/README.md
(hopefully already fixed in Crowdin, although I'm not quite sure how that translates MarkDown to HTML and back again)
- fix MarkDown syntax in German translation
- add newline at end-of-file (GitHub's online editor did that automatically)
=> fix MarkDown syntax in German translation

.travis.yml
- remove cached-directory entry that
- contained a typo
- probably wouldn't have matched anything, anyway, as the [cached-directory paths are relative to the `$TRAVIS_BUILD_DIR`](https://docs.travis-ci.com/user/caching/#arbitrary-directories), which already would be the cloned Git repo root.
- add [shortcut to cache NPM packages](https://docs.travis-ci.com/user/caching/#npm-cache)
Fixes #1469
=> cache NPM packages on Travis CI

LANGS.md
- remove the "(beta)" designation from "Deutsch" in the language listing
Rationale:
The German translation is recently and currently very well-maintained and kept closely up-to-date with the English tutorial. Most recent changes and additions to it have been peer-proofread. The remainder is by now field-proven through use in various workshops.
=> consider the German translation stable and remove the "(beta)" designation

es/python_installation/instructions.md
This change fix the command line section for installing Python on Debian and it derivatives.
=> Fix command for installation on Debian and Ubuntu

en/django_forms/README.md
- Code Fix:
added missing slash, so that code snippet is consistent with the immediately preceding one.
Other than claimed in the original description, skipping the slash doesn't cause any technical problems, but the inconsistency might confuse readers.
- Code Fix:
added missing slash, since the original produced an error when implemented
=> add slash to make code snippet consistent

es/django_start_project/README.md
En el párrafo de configuración de rutas para archivos estáticos, modifica nombre de variable STATIC_ROOR por STATIC_ROOT
- Changes variable name from STATIC_ROOR to STATIC_ROOT
=> Corrige nombre de variable STATIC_ROOT

en/intro_to_command_line/README.md
Issue #1494 started when the include file was created (`git diff eab1dcde...5b3c5ca53`), this fixes it.
=> Add necessary blank line for the first section in open_instructions.md  Fixes #1494

en/django_models/README.md
Hey, I noticed this issue, and this could be fixed fairly easily. I did it only for English, I did not check any of the other languages. If you would like me to, I could.
- Add a line to django_models tutorial page
=> Django apps have their own urls.py file

en/styles/website.css
This addresses issues #1054 and #1055 although may not satisfy all the ideas/requests from the original reporter.  Further changes I think would involve gitbook core or theme customizations, which would be a much bigger undertaking.
I could also hide the social sharing icons in the upper right, to declutter that if we don't think they are useful.  I wasn't sure though.
=> Add text to prev/next and top menu icons, so they are easier to notice and understand

.github/CODEOWNERS
Add [GitHub CODEOWNERS](https://help.github.com/en/articles/about-code-owners) using the existing PR review teams from https://github.com/orgs/DjangoGirls/teams (an idea brought up by https://github.com/DjangoGirls/tutorial/issues/1271#issuecomment-392542583)
This will automatically request reviews of the respective teams for pull requests touching "their" files, but won't require these reviews for merging.
=> add GitHub CODEOWNERS using the existing PR review teams

en/intro_to_command_line/open_instructions.md
Fixes a small bug where Windows information wasn't inside of the collapsible section under "Brief intro to the command line": https://tutorial.djangogirls.org/en/installation/#brief-intro-to-the-command-line
I've tested this locally using `gitbook serve` to confirm it fixes the issue. Seems like it's really a bug in gitbook but easy enough for us to fix on our side.
- Added a single line to `en/intro_to_command_line/open_instructions.md`
=> Fix bug where Windows information isn't collapsing in intro to command line

en/django_installation/instructions.md, en/django_urls/README.md
Corrected name of function being imported from 'url' to 'path' under the blog.urls section
The line I changed indicated that we were importing the url function from django.urls, when we are in fact importing the path function from django.urls.
This was confusing the first time I read it
=> Add VS code powershell activation code

en/extend_your_application/README.md
Chapter: Extending your application
This line
> We want to have a link from a post's title in the post list to the post's detail page. Let's change `<h1><a href="">{{ post.title }}</a></h1>` so that it links to the post's detail page:
Should be changed to 
> We want to have a link from a post's title in the post list to the post's detail page. Let's change `<h2><a href="">{{ post.title }}</a></h2>` so that it links to the post's detail page:
-
-
-
=> Changed h1 to h2

en/styles/website.css
This is a followup for #1495 to address feedback in this comment: https://github.com/DjangoGirls/tutorial/pull/1495#issuecomment-479446680
It changes small screens from:
To be like:
=> Make navigation bar fit better on small screens. Reword to Show Outline

en/python_installation/instructions.md
Added it to the Note at the bottom about handling "command not found" on Windows.
I considered adding a note in the Windows installation instructions, telling the user to close any pre-open command prompt. This is probably better operationally (prevent the error instead of handle it), but I couldn't find a satisfactory way to put it in the narrative.
=> Add note about pre-opened cmd on Windows

book.json, en/deploy/README.md, en/django_admin/README.md, en/django_forms/README.md, en/django_models/README.md, en/django_start_project/README.md, en/django_urls/README.md, en/django_views/README.md, en/dynamic_data_in_templates/README.md, en/whats_next/README.md
closes #1536
I verified the tutorial with the following combinations: 
- OSX + Python3.6.9 + Django2.2.4
- Windows10 + Python3.6.8 + Django2.2.4
It worked fine except for deployment to PythonAnywhere.
I commented on each commit where it was corrected.
Thank you.
=> Update Django version to 2.2 LTS

book.json
The original sectionx plugin has a [bug][1] that manifests itself in the
Django Girls tutorial. The initial state of the arrow used to expand
operating-system-specific sections is wrong and can cause confusion.
The creator of sectionx has not been responsive in a [Pull Request to fix
the issue][2]. Another user has created a fork which includes the fix
and we can benefit from that.
[1]: https://github.com/ymcatar/gitbook-plugin-sectionx/issues/6
[2]: https://github.com/ymcatar/gitbook-plugin-sectionx/pull/7
=> Use fork of sectionx plugin to fix arrow direction

en/SUMMARY.md, en/django_forms/README.md, en/django_urls/README.md, en/extend_your_application/README.md
- in prose, spell "URL" all uppercase (rather than all lowercase "url" or with only initial capital "Url")
- when "url" refers to the module name (defined by `url.py`), mark it up as code (i.e. "`url`") 
I've found these occurrences with:
```bash
git grep -P '(?<!% |\.|_|`|c|/)[Uu]rl(?!s.py|patterns|resolver)' -- en/
```
=> fix capitalization of "URL"

es/django_forms/README.md
An unnecessary relative path to a view in a redirect
-
-
-
=> deleted blog.views. from def  post_new(requests)

sk/python_introduction/README.md
- unify variable name (translated) throw whole page
=> sk/python_introduction - fix lottery variable name

en/django_urls/README.md
It is introduced earlier in the tutorial that on windows, control + break can be used instead of control + c. From experience I know it is a good idea to repeat that here in the tutorial, as students may have forgotten. This will save them some confusion.
-
-
-
=> Control + break for windows

es/deploy/README.md, es/django_templates/README.md, es/dynamic_data_in_templates/README.md, es/intro_to_command_line/README.md, es/python_introduction/README.md
The terminal command "exit" shouldn't be translated.
- the word "**salida**" was corrected to the command name "**exit**"
=> Fix issues on the Spanish translation

en/SUMMARY.md
- spell "GitHub" with capital "H"
=> fix capitalization of "GitHub"

es/django_forms/README.md, es/django_orm/README.md, es/django_start_project/README.md, es/django_urls/README.md, es/django_views/README.md, es/whats_next/README.md
- add some missing "¡"
- replace "à", "è", "ì", "ò", "ù" by "á", "é", "í", "ó", "ú"
in the es translation
=> master: Fix es typos

en/css/README.md
The css section of the English tutorial had an external link to codeacademy, but it is no longer free. To fix the bug, I modified the link to freeCodeCamp which has a free HTML and CSS course.
=> fix Codecademy CSS/HTML course link broken, update for freeCodeCamp link (resolves #1572)

en/SUMMARY.md
-Naming conflicts on `virtual-environment` so the summary panel shortcut wasn't working. Updated it to use the section heading instead.
=> Update anchor reference for virtual env

en/django_forms/README.md
rephrase sentence to make clear which element the name `page-header` refers to. (It's the `div`, not the link.)
This should fix the ambiguity noticed in PR #1589, which has been reverted with PR #1590.
See https://github.com/DjangoGirls/tutorial/pull/1589#pullrequestreview-300581137
/cc @PierreGuilmin
=> rephrase sentence to fix "page header" ambiguity

en/django_installation/instructions.md
I added a note about the directory structure in the description of `requirements.txt` .
This is because beginners are confused because the description of the `venv` directory is not written.
=> Indicate that directory venv is also there when showing where to put requirements.txt

en/django_models/README.md
Fixes #1535. `python manage.py startapp blog` doesn’t create this file: https://stackoverflow.com/questions/45002225/why-isnt-urls-py-generated-with-django-admin-startapp-mysite
=> Remove urls.py from startapp blog file listing (#1535)

en/django_models/README.md, en/django_start_project/README.md
List dir `myvenv/` in file trees and fix nested tree display.
Also, order entries the way [`tree`](https://en.wikipedia.org/wiki/Tree_(command)) does.
The new version of the listings were created by running
```bash
tree -L 3 djangogirls -I *.pyc -I __pycache__
```
from the directory containing the `djangogirls` directory and then manually replacing the subtree below `myvenv` with just `...` and removing the line at the end with the number-of-files statistic.
=> list dir myvenv/ in file trees and fix nested tree display

en/django_installation/instructions.md
Add an HTML comment to separate the two blockquote blocks, so that GitBook and Crowdin don't merge them into a single block.
See https://github.com/DjangoGirls/tutorial/pull/1603#discussion_r336930974
=> separate blockquote blocks

es/css/README.md
With previous snippet the result did not match the screenshot.
Also, the text before mentions modifying a CSS snippet previously implemented as:
```css
h1 a, h2 a {
color: #C25100;
}
```
=> [Spanish] [CSS] Fix selector of headings when changing font family

es/django_forms/README.md
Base template is located at `blog/templates/blog/base.html` but path displayed before code snippets refers to `blog/templates/blog/post_base.html`.
=> [Spanish] [django_forms] Fix base.html file path in code snippets

en/python_introduction/README.md
The original explanation says that we re-write the name of the example function at the bottom of the file "because Python reads the file from top to bottom, so we need to re-write the name of the function." I find that explanation a bit confusing myself; the primary reason that we need to write `hi()` is because we need to execute it, not because of Python's ordering properties.
I think two things were conflated here:
1) The difference between defining and running a function
2) Explaining that Python reads files from top to bottom, and needs functions to be defined before they can be called
I tried to more explicitly explain that what we're doing is calling a function we just defined, and break these concepts apart more. Very open to feedback on ways to do this better.
=> Clarify calling functions explanation

cs/deploy/README.md, es/deploy/README.md, hu/deploy/README.md, it/deploy/README.md, ko/deploy/README.md, pl/deploy/README.md, pt/deploy/README.md, ru/deploy/README.md, tr/deploy/README.md, uk/deploy/README.md, zh/deploy/README.md
The output from git is given as though a first commit has already been made. This corrects it to show that no commits have been made yet.
=> Change `git status` output to reflect no previous commit

en/extend_your_application/README.md
- Replace "Let's type" from #1606 with "Enter" as it some participants may want to copy-paste it instead of typing all that manually, and that's OK.
=> Replace "Let's type" with "Enter"

de/django_forms/README.md, de/extend_your_application/README.md, de/html/README.md, de/python_introduction/README.md
* armorgames (https://crowdin.com/profile/armorgames)
* Fiddl0r (https://crowdin.com/profile/Fiddl0r)
* Raphael Das Gupta (https://crowdin.com/profile/das-g)
=> German translation improvements from Crowdin made by:

fr/css/README.md, fr/django_forms/README.md, fr/extend_your_application/README.md, fr/python_installation/instructions.md, fr/python_introduction/README.md
* ariasuni (https://crowdin.com/profile/ariasuni)
=> French translation improvements from Crowdin made by:

en/python_installation/instructions.md
- Moved the line "Press the Windows key and Pause/Break key at the same time" to the bottom of the list as Microsoft Laptops no-longer have a Pause/Break Key on the keyboard.
- Added a line to say "Press the Windows key and start to type System Information..." as this is the quickest way on a Win10 machine (imo - I'm not fussed about order or priority, but think it should be in there)
- Just wanted to call out that the published website I was reading does not match the Master Branch, so perhaps it could be deployed before Saturday, because what is there now, without my little pull request is already better than what is currently published.
=> Add another option to access System Information on Windows

en/dynamic_data_in_templates/README.md
When I was reading through the tutorial, I got to this section and read:
```
The last missing part is passing the `posts` QuerySet to the template context.
Don't worry – we will cover how to display it in a later chapter.
```
On a first read, this confused me -- I thought in both sentences we were talking about the same action (passing `posts` into the `render` call and displaying it in the template); making it additionally confusing that we were doing _some_ work in this chapter about passing in posts.
I wondered whether the "next chapter" sentence was even necessary, and found this in the commit logs: https://github.com/DjangoGirls/tutorial/commit/8db3c9174e1754bbaaaa07535d4fe35ffa98713a.
Noting that the ordering of the sentences had confused participants, and they apparently wanted to …
=> Be more explicit about next steps with QuerySet

en/chromebook_setup/README.md, en/deploy/README.md, en/django_installation/README.md, en/python_installation/README.md
- write "installation steps" in lowercase (But keep "Installation chapter" with an upper case "I", as it refers to a
title.)
=> write "installation steps" in lowercase

en/deploy/README.md
See https://github.com/DjangoGirls/tutorial/commit/be2f0b0f306dd82d79a6e6f0516a09cca90e560d#r45123764 (Thanks for pointing this out, @nikhiljohn10)
- limit gitignore entry for directories called `static/` to the one at the project root, i.e., don't exclude directories called `static` elsewhere in the project from being tracked by Git
These non-toplevel directories are needed to store static files in the source tree, see [Where to put static files for Django](https://tutorial.djangogirls.org/en/css/#where-to-put-static-files-for-django) in our CSS chapter. The top-level folder corresponds to the `STATIC_ROOT` setting we set [when setting up the Django project and its settings](https://tutorial.djangogirls.org/en/django_start_project/#changing-settings). It's …
=> ignore only top-level static/ dir, not every one

en/css/README.md, en/django_forms/README.md
Use term "element" to refer to HTML elements as a whole, and only use "tag" when referring to the tags (usually) delimiting it (or when talking about Django template tags or Git tags, of course.)
- replace "tag" by "element" where appropriate
=> use term "element" to refer to HTML elements as a whole

en/django_forms/README.md, en/html/README.md
- replace "as follow" by "as follows"
- add indefinite articles ("a") at some places
- specify that the stuff mentioned at https://github.com/DjangoGirls/tutorial/blob/11e71b5b351292f54648b615712ebea3ebc77b9a/en/html/README.md#L155 indeed are (HTML) _"elements"_
- minor rephrasing (11e71b5) for more natural language flow
(I noticed this when trying to translate the changes from #1681 to German.)
=> fix grammar: "as follow" -> "as follows", add articles, minor rephrasing

en/html/README.md
These can't be "another two" article elements if no other article elements have been mentioned, yet. (Previously they were `div` elements and the now-`header` element preceding them was then also a `div`. But since #1681 not anymore.)
- replace "**Another** two `article` elements" with "**The** two `article` elements"
=> fix logic: These can't be "another two" article elements

en/django_start_project/README.md
- d7d128d add blank lines before` {% filename %}` so that Crowdin won't lose the linebreak and thereby break the markup (See https://crowdin.com/translate/django-girls-tutorial/306/en-de#14746)
- b53c420 change code block label, as `python -c ...` is for the command line, not the `.env` file
- 3a0cbae minor rephrasing, so that the sentence flows more IMO naturally: "a little further, in the same file<strong>,</strong> we inject ..." &rarr; "a little further **down** in the same file, we inject ..."
=> Blank line before filename macro

cs/django_models/README.md, es/django_models/README.md, fa/django_models/README.md, hu/django_models/README.md, pl/django_models/README.md, sk/django_models/README.md, tr/django_models/README.md, uk/django_models/README.md, zh/django_models/README.md
`settings.AUTH_USER_MODE` was already being used in many languages, but not all of them. This PR changes the pending languages still using the old way to reference the User model.
=> Fix: Consistently use settings.AUTH_USER_MODE in all languages

en/css/README.md, en/django_forms/README.md, en/template_extending/README.md
According to the official Bootstrap migration guides:
* https://getbootstrap.com/docs/4.0/migration/
* https://getbootstrap.com/docs/5.0/migration/
Apparently, the only change affecting this project comes from the v4 migration guide:
> * Renamed .btn-default to .btn-secondary.
=> Upgrade project to Bootstrap v5

README.md
URLs pointing to GitBook now redirect to the current version of GitBook, thus being unusable to check what was the intended link content (e.g. https://legacy.gitbook.com/).
Also, I haven't been able to find a usable GitBook Editor link, but instead needed to run `npm honkit serve` locally to visualize local changes.
Closes #1726
=> Replace GitBook with HonKit in Readme file

en/django_templates/README.md
In commit https://github.com/DjangoGirls/tutorial/commit/a9dbbf582e5e863bbb4ef50a16201a2b758a81f9, the `<div>` tags for the blog posts where changed to `<article>`, but this reference wasn't updated.
=> Fix: Refer to article tags instead of div

es/django_start_project/README.md
- This uses the `/` operator for `Path` objects to concatenate paths, instead of relying on the `os` module.
Resolves #1763
=> [es] Using `Path.__truediv__` instead of `os` module.

en/code_editor/instructions.md
Atom will be [sunset](https://github.blog/2022-06-08-sunsetting-atom/) and unmaintained after December 15th 2022.
=> Remove Atom from code editor suggestions

ja/django_templates/README.md
- Fix broken links in Japanese text
before
after
=> Fix broken links in Japanese text

book.json, package.json
- Replace gitbook-plugin-sidebar-ad with gitbook-plugin-sidebar-ads
- Add sponsor ads to book.json and extra ad for Django Girls
The new ad looks like the video below:
https://user-images.githubusercontent.com/13593285/227919231-c0b9d8d5-1e3c-4498-a501-26ba683ec146.mov
=> Replace sidebar-ad with sidebar-ads plugin

.github/workflows/deploy.yml
This uses the currently beta feature of using GitHub Actions to deploy GitHub Pages, rather than using a gh-pages branch. This keeps the repository size smaller.
While this feature is beta, it is used [by default](https://github.blog/2022-08-10-github-pages-now-uses-actions-by-default/).
This does require a change on the repo itself and since I don't have the permissions, someone else will need to do this. https://github.blog/changelog/2022-07-27-github-pages-custom-github-actions-workflows-beta/ shows how to.
This will make it easier to publish large artifacts, such as ebooks (see https://github.com/DjangoGirls/tutorial/issues/1785).
=> Switch to actions/deploy-pages

en/deploy/README.md, en/deploy/install_git.md
With older versions of git the command to rename the branch fails if there is no branch yet. We're also making the tutorial harder than it needs to be.
This ignores it and simply uses the default by pushing HEAD instead of main. GitHub is then smart enough to use that as default. Future clones will also simply copy the default branch from GitHub.
Fixes #1779
=> Ignore the default branch name problem

en/css/README.md, en/django_forms/README.md, en/template_extending/README.md
Simplifies the `link` element used for Google Fonts, so it’s easier for beginners to follow:
- Its attributes should use the same quote style as other elements.
- `rel="stylesheet"` should come first, to match other `link` elements.
- No need for a protocol-relative URL, we can load the HTTPS version everywhere.
- `type="text/css"` does nothing, it can be removed.
=> Simplify Google Fonts link element

en/cloud_development_setup/instructions.md
This essentially copies the "Virtual environment" and "Working with virtualenv: Linux and OS X" over to RunCode. There is no need to install and use `virtualenv` on RunCode specifically, the built-in `python -m3 venv myvenv` works fine there as well.
And for other environments we use `source` rather than `.` to initialise the virtual environment, so we should do the same here for consistency.
=> Simplify RunCode virtual environment installation and usage instructions

en/cloud_development_setup/instructions.md, en/intro_to_command_line/open_instructions.md, en/python_introduction/prompt.md
fixes #1805
- Remove suggestions to use Jupyter Lab workspace in RunCode, as (for this tutorial) there's probably no advantage to use a Jupyter Lab workspace over using RunCode's default VSCode based workspaces, but indeed some disadvantages, as #1805 mentions. (Fewer unneeded options to choose from also simplifies the work of coaches and of those maintaining the tutorial.)
- Remove all mentions of how to open a command line window or Python prompt in a Jupyter Lab workspace
- Completely remove the special case for RunCode users in the "Python prompt" section, as at that point, they've already been told to follow Linux instructions.
=> remove suggestions to use Jupyter Lab workspace

en/cloud_development_setup/instructions.md, en/intro_to_command_line/open_instructions.md
After selecting the "Blank" workspace type, there is another step to select a size. I think it helps if the tutorial explicitly says which size should be used. And acknowledges it takes a while for it to start.
Additionally, in "intro to command line", it’d be clearer for users if they reused the workspace they’ve created before, rather than having multiple ones to manage.
=> Provide more information for RunCode users choosing a workspace

de/python_installation/instructions.md
It seems variable substitution only works in fenced not indented code blocks.
---
- Fix variable substitution in German tutorial
=> Fix variable substitution in German tutorial

.github/workflows/deploy.yml, .github/workflows/test.yml
- Update github acitions to latest versions
=> chore: update github actions

en/deploy/README.md
This error was frequently encountered when pushing/pulling from github
=> instructions to create github access token

book.json, en/README.md
The `gitter.im` chat seems to be abandoned between DjangoGirls events, and is filled with **very bad** spam (I'm not repeating here the things that are inside the chat), so maybe it's better to remove the links for now, if the chat isn't moderated, to avoid looking bad if someone clicks on the link(s) and enters there.
- Removed the `gitter.im` links from the `README.md` file
- Removed the `gitter.im` link from the sidebar
I did the work only in the English language file.
=> Remove gitter.im links from the homepage and the sidebar

.github/workflows/deploy.yml, en/README.md
~See a run of these actions [here](https://github.com/das-g/django-girls-tutorial/actions/runs/4824138230).~
~Results available from `https://das-g.github.io/django-girls-tutorial/book_<lang>.epub`, e.g. for English https://das-g.github.io/django-girls-tutorial/book_en.epub~
~Before merging this, we'll probably want to have more meaningful file names, e.g. `django-girls-tutorial_en.epub`.~
Results available from `https://das-g.github.io/django-girls-tutorial/django-girls-tutorial_<lang>.epub`, e.g. for English https://das-g.github.io/django-girls-tutorial/django-girls-tutorial_en.epub
closes #1785
=> build and deploy ePub e-book files

.github/workflows/deploy.yml, .github/workflows/test.yml
<del>I'm unsure why this broke.</del> I also looked at https://honkit.netlify.app/ebook which mentions you can publish an ebook with a specific name, but figured this was the shortest path. It's untested now.
Right after submitting this I had a theory why it broke. On the first run it passed, but after that it started to fail. The first run it couldn't have cached the package with `awalsh128/cache-apt-pkgs-action` while it has on the later runs.
`/usr/bin/rename` is provided via alternatives:
```
Setting up rename (2.02-1) ...
update-alternatives: using /usr/bin/file-rename to provide /usr/bin/rename (rename) in auto mode
update-alternatives: warning: skip creation of /usr/share/man/man1/rename.1.gz because associated file /us
r/share/man/man1/file-rename.1p.gz (of link group rename) …
```
=> Use Ubuntu 24.04 for rename from util-linux

.github/workflows/deploy.yml
- Add command to install `rename` to fix `rename: command not found` error.
=> Install rename in Github deploy workflow

it/django_admin/README.md
- Fixed  a typo from `python manage.py crearesuperutente ` to `python manage.py createsuperuser`
=> Fixed typo in italian translation

en/django_views/README.md
I made the intro to the chapter more precise, more clear and more technical.
I split what the view does in 3 clear steps. Each step contains one highlighted technical word (`request`, `model`, `template`) which makes it easier to understand which technical thing is responsible for what. The first step acknowledges that the views receive `request` data as a parameter. The previous version wasn't explicit about it but I think it is important because the `request` is a parameter of a function we are about to write. I added an example of what does "logic" mean in the context of "views are where we put the logic of our application" to the second step. The third step is about filling a `template`. I think "filling a template" is better wording than "passing it to a template".
I rewrote the …
=> Django views — improve the intro paragraph

en/django_forms/README.md
I removed the sentence "You should not rename POST to anything else (the only other valid value for method is GET, but we have no time to explain what the difference is)" and I added a brief explanation that GET is for getting pages and POST is for sending forms. I also added explicit mention of the `request.method` field to the paragraph so that the readers will recognise it later in code.
I know that the world is more complicated than "GET is for getting pages and POST is for sending forms" (one can send forms with GET) but I think giving that general idea helps with reading the code that follows (when we compare the `request.method` with `"POST"`) and this is not a complete lie.
=> Django forms: POST vs GET explanation

en/css/README.md
I'm adding a 15px margin to make the edit button look prettier.
It was like this
Now it's like this
=> CSS: Add margin to the edit button

en/django_forms/README.md
In my previous fix #1864 to the Django Forms page I introduced an inaccuracy: I called an instance member "field" instead of "attribute". That pull request fixes that. Thank @das-g for noticing.
I also noticed a typo in the same sentence: I wrote "form" instead of "from". I fix it, too.
=> Django Forms: rename field to attribute to be more accurate; fix typo

en/django_start_project/README.md
Two attendees in my group got confused by this today.
=> Add a helpful note re: timezone formats

en/deploy/README.md
When we get to the `git push` stage, the tutorial currently tells people to attempt to use their normal github username and password.
It goes on to say "oh you will probably get an error", and tells people to create a PAT instead.
GitHub actually removed username & password auth in 2021.
So let's just tell people to use a PAT up-front.
ALSO: the tutorial used to tell people to follow the instructions on GitHub, but then also included its own instructions, inline. So I've removed them in favour of making github the single source of truth.
=> Tell people to create a GitHub Personal Access Token up-front

en/django_forms/README.md
- fixing spelling in english readme
=> fix spelling
